#!/usr/bin/env python3
"""Parse Lynne's final 2025 sheet (Football_2025-54.xlsx) into migration
SQL for the read-only archive.

Verified structure:
  - 1,265 physical rows; only rows with an integer NO. and a string NAMES
    are entries — 56 of them in the final sheet (she deletes eliminated
    entries as the season goes, so this is a shrinking working sheet, not
    a roster).
  - Week headers are mixed case ('Week 1'..'Week 4', then 'WEEK 5'..) —
    parsed case-insensitively.
  - STATUS IS IN THE FILL COLOR of the NAMES cell (styled workbook, not
    data_only): FFFF0000 red = OUT, FFFFFF00 yellow = the 27 winners
    (one loss/bye standing at season end).
  - Rows 60-70 hold her stats block: weekly No Losses / Loss/Bye / Out
    counts and the payout math (27 winners x $1,008.60).

Usage: python3 scripts/archive/parse-2025.py Football_2025-54.xlsx
Writes: supabase/migrations/20260824000017_archive_2025.sql
"""
import json
import re
import sys

import openpyxl

SRC = sys.argv[1] if len(sys.argv) > 1 else "Football_2025-54.xlsx"
OUT = "supabase/migrations/20260824000017_archive_2025.sql"

styled = openpyxl.load_workbook(SRC)
values = openpyxl.load_workbook(SRC, data_only=True)
ws = styled[styled.sheetnames[0]]
wv = values[values.sheetnames[0]]

# --- headers: NO., NAMES, then 18 week columns, case-insensitive ----------
headers = [ws.cell(1, c).value for c in range(1, ws.max_column + 1)]
assert headers[0] == "NO." and headers[1] == "NAMES", headers[:2]
week_cols = []
for i, h in enumerate(headers[2:], start=3):
    m = re.fullmatch(r"week\s*(\d+)", str(h).strip(), re.IGNORECASE)
    assert m, f"unexpected week header {h!r}"
    week_cols.append((int(m.group(1)), i))
assert [w for w, _ in week_cols] == list(range(1, 19)), week_cols

FILL_STATUS = {"FFFF0000": ("red", "out"), "FFFFFF00": ("yellow", "winner")}

entries = []
skipped = 0
for r in range(2, ws.max_row + 1):
    no = wv.cell(r, 1).value
    name = wv.cell(r, 2).value
    if not isinstance(no, int) or not isinstance(name, str):
        skipped += 1
        continue
    fill = ws.cell(r, 2).fill
    rgb = None
    if fill is not None and fill.patternType is not None:
        rgb = getattr(fill.start_color, "rgb", None)
    assert isinstance(rgb, str) and rgb in FILL_STATUS, (
        f"row {r} ({name!r}): unexpected fill {rgb!r} on an entry row"
    )
    fill_name, outcome = FILL_STATUS[rgb]
    picks = []
    for wk, col in week_cols:
        v = wv.cell(r, col).value
        picks.append(str(v).strip() if v is not None and str(v).strip() else None)
    entries.append(
        {"no": no, "name": name.strip(), "fill": fill_name, "outcome": outcome, "picks": picks}
    )

# --- her weekly bucket history (stats block rows 60-62) -------------------
def block_row(label_row):
    return [wv.cell(label_row, c).value for c in range(3, 21)]

no_losses = block_row(60)
loss_bye = block_row(61)
out = block_row(62)
assert wv.cell(60, 2).value == "NO LOSSES"
assert str(wv.cell(61, 2).value).startswith("1 LOSS")
assert wv.cell(62, 2).value == "OUT"

# --- verify against the season facts --------------------------------------
winners = [e for e in entries if e["outcome"] == "winner"]
outs = [e for e in entries if e["outcome"] == "out"]
print(f"entries: {len(entries)} (winners {len(winners)}, out {len(outs)}), non-entry rows skipped: {skipped}")
assert len(winners) == 27, "the payout block says 27 winners"
mine = {e["no"]: e["name"] for e in entries if e["no"] in (980, 1006, 1037)}
assert mine == {980: "Anthony DellaPia 5", 1006: "Alexc 1", 1037: "Nolan Lawrence 1"}, mine

esc = lambda s: s.replace("'", "''")
rows_sql = ",\n".join(
    f"  ({e['no']}, '{esc(e['name'])}', '{e['fill']}', '{e['outcome']}', '{esc(json.dumps(e['picks']))}'::jsonb)"
    for e in sorted(entries, key=lambda e: e["no"])
)
weekly_sql = ",\n".join(
    f"  ({wk}, {no_losses[wk-1] if no_losses[wk-1] is not None else 'null'}, "
    f"{loss_bye[wk-1] if loss_bye[wk-1] is not None else 'null'}, "
    f"{out[wk-1] if out[wk-1] is not None else 'null'})"
    for wk in range(1, 19)
)

sql = f"""-- V2 Part G: Lynne's final 2025 sheet as a read-only archive.
-- GENERATED by scripts/archive/parse-2025.py from Football_2025-54.xlsx.
-- Status came from the FILL COLOR of the NAMES cells (red = OUT, yellow =
-- the 27 winners); week headers were mixed case and parsed
-- case-insensitively. She deletes eliminated entries as the season goes,
-- so only {len(entries)} of ~1,245 entries remain in the final sheet — a
-- missing entry is NOT a data error. Structurally separate from every
-- 2026 table; no write policies exist.

create table archive_2025_entries (
  lynne_number int primary key,
  entry_name text not null,
  fill text not null check (fill in ('red', 'yellow')),
  outcome text not null check (outcome in ('winner', 'out')),
  picks jsonb not null  -- 18 values: team name, 'BYE', 'OUT', or null
);

create table archive_2025_weekly (
  week int primary key check (week between 1 and 18),
  no_losses int,
  loss_bye int,
  out int
);

alter table archive_2025_entries enable row level security;
alter table archive_2025_weekly enable row level security;
create policy "public_read_archive_2025_entries" on archive_2025_entries
  for select using (true);
create policy "public_read_archive_2025_weekly" on archive_2025_weekly
  for select using (true);
grant select on archive_2025_entries, archive_2025_weekly to anon, authenticated;

insert into archive_2025_entries (lynne_number, entry_name, fill, outcome, picks) values
{rows_sql};

insert into archive_2025_weekly (week, no_losses, loss_bye, out) values
{weekly_sql};
"""
with open(OUT, "w") as f:
    f.write(sql)
print(f"wrote {OUT}")
