-- Broadcast networks for every announced 2026 game, from ESPN's public
-- scoreboard (fetched 2026-08-24). 248 of 272 games have a network;
-- the 24 nulls are unannounced flex slots (all of week 18, four late
-- Saturday slots in weeks 16-17) and stay null until the league flexes
-- them. Update by (week, away, home) so a wrong id can never mislabel.

update nfl_games set network = 'NBC' where week = 1 and away_team = 'NE' and home_team = 'SEA';
update nfl_games set network = 'Netflix' where week = 1 and away_team = 'SF' and home_team = 'LAR';
update nfl_games set network = 'FOX' where week = 1 and away_team = 'TB' and home_team = 'CIN';
update nfl_games set network = 'FOX' where week = 1 and away_team = 'NO' and home_team = 'DET';
update nfl_games set network = 'CBS' where week = 1 and away_team = 'NYJ' and home_team = 'TEN';
update nfl_games set network = 'CBS' where week = 1 and away_team = 'BAL' and home_team = 'IND';
update nfl_games set network = 'FOX' where week = 1 and away_team = 'ATL' and home_team = 'PIT';
update nfl_games set network = 'FOX' where week = 1 and away_team = 'CHI' and home_team = 'CAR';
update nfl_games set network = 'CBS' where week = 1 and away_team = 'CLE' and home_team = 'JAX';
update nfl_games set network = 'CBS' where week = 1 and away_team = 'BUF' and home_team = 'HOU';
update nfl_games set network = 'FOX' where week = 1 and away_team = 'MIA' and home_team = 'LV';
update nfl_games set network = 'CBS' where week = 1 and away_team = 'GB' and home_team = 'MIN';
update nfl_games set network = 'FOX' where week = 1 and away_team = 'WAS' and home_team = 'PHI';
update nfl_games set network = 'CBS' where week = 1 and away_team = 'ARI' and home_team = 'LAC';
update nfl_games set network = 'NBC' where week = 1 and away_team = 'DAL' and home_team = 'NYG';
update nfl_games set network = 'ESPN/ABC' where week = 1 and away_team = 'DEN' and home_team = 'KC';
update nfl_games set network = 'Prime Video' where week = 2 and away_team = 'DET' and home_team = 'BUF';
update nfl_games set network = 'FOX' where week = 2 and away_team = 'CAR' and home_team = 'ATL';
update nfl_games set network = 'FOX' where week = 2 and away_team = 'MIN' and home_team = 'CHI';
update nfl_games set network = 'FOX' where week = 2 and away_team = 'PHI' and home_team = 'TEN';
update nfl_games set network = 'CBS' where week = 2 and away_team = 'PIT' and home_team = 'NE';
update nfl_games set network = 'FOX' where week = 2 and away_team = 'GB' and home_team = 'NYJ';
update nfl_games set network = 'CBS' where week = 2 and away_team = 'CLE' and home_team = 'TB';
update nfl_games set network = 'CBS' where week = 2 and away_team = 'NO' and home_team = 'BAL';
update nfl_games set network = 'CBS' where week = 2 and away_team = 'CIN' and home_team = 'HOU';
update nfl_games set network = 'CBS' where week = 2 and away_team = 'JAX' and home_team = 'DEN';
update nfl_games set network = 'CBS' where week = 2 and away_team = 'LV' and home_team = 'LAC';
update nfl_games set network = 'FOX' where week = 2 and away_team = 'WAS' and home_team = 'DAL';
update nfl_games set network = 'FOX' where week = 2 and away_team = 'SEA' and home_team = 'ARI';
update nfl_games set network = 'FOX' where week = 2 and away_team = 'MIA' and home_team = 'SF';
update nfl_games set network = 'NBC' where week = 2 and away_team = 'IND' and home_team = 'KC';
update nfl_games set network = 'ESPN/ABC' where week = 2 and away_team = 'NYG' and home_team = 'LAR';
update nfl_games set network = 'Prime Video' where week = 3 and away_team = 'ATL' and home_team = 'GB';
update nfl_games set network = 'FOX' where week = 3 and away_team = 'LAC' and home_team = 'BUF';
update nfl_games set network = 'FOX' where week = 3 and away_team = 'CAR' and home_team = 'CLE';
update nfl_games set network = 'FOX' where week = 3 and away_team = 'NYJ' and home_team = 'DET';
update nfl_games set network = 'CBS' where week = 3 and away_team = 'HOU' and home_team = 'IND';
update nfl_games set network = 'CBS' where week = 3 and away_team = 'KC' and home_team = 'MIA';
update nfl_games set network = 'CBS' where week = 3 and away_team = 'TEN' and home_team = 'NYG';
update nfl_games set network = 'CBS' where week = 3 and away_team = 'CIN' and home_team = 'PIT';
update nfl_games set network = 'FOX' where week = 3 and away_team = 'SEA' and home_team = 'WAS';
update nfl_games set network = 'CBS' where week = 3 and away_team = 'NE' and home_team = 'JAX';
update nfl_games set network = 'FOX' where week = 3 and away_team = 'ARI' and home_team = 'SF';
update nfl_games set network = 'FOX' where week = 3 and away_team = 'MIN' and home_team = 'TB';
update nfl_games set network = 'CBS' where week = 3 and away_team = 'BAL' and home_team = 'DAL';
update nfl_games set network = 'CBS' where week = 3 and away_team = 'LV' and home_team = 'NO';
update nfl_games set network = 'NBC' where week = 3 and away_team = 'LAR' and home_team = 'DEN';
update nfl_games set network = 'ESPN/ABC' where week = 3 and away_team = 'PHI' and home_team = 'CHI';
update nfl_games set network = 'Prime Video' where week = 4 and away_team = 'PIT' and home_team = 'CLE';
update nfl_games set network = 'NFL Net' where week = 4 and away_team = 'IND' and home_team = 'WAS';
update nfl_games set network = 'CBS' where week = 4 and away_team = 'NE' and home_team = 'BUF';
update nfl_games set network = 'FOX' where week = 4 and away_team = 'NYJ' and home_team = 'CHI';
update nfl_games set network = 'CBS' where week = 4 and away_team = 'JAX' and home_team = 'CIN';
update nfl_games set network = 'CBS' where week = 4 and away_team = 'ARI' and home_team = 'NYG';
update nfl_games set network = 'FOX' where week = 4 and away_team = 'LAR' and home_team = 'PHI';
update nfl_games set network = 'FOX' where week = 4 and away_team = 'GB' and home_team = 'TB';
update nfl_games set network = 'CBS' where week = 4 and away_team = 'TEN' and home_team = 'BAL';
update nfl_games set network = 'FOX' where week = 4 and away_team = 'DAL' and home_team = 'HOU';
update nfl_games set network = 'FOX' where week = 4 and away_team = 'MIA' and home_team = 'MIN';
update nfl_games set network = 'CBS' where week = 4 and away_team = 'KC' and home_team = 'LV';
update nfl_games set network = 'CBS' where week = 4 and away_team = 'DEN' and home_team = 'SF';
update nfl_games set network = 'CBS' where week = 4 and away_team = 'LAC' and home_team = 'SEA';
update nfl_games set network = 'NBC' where week = 4 and away_team = 'DET' and home_team = 'CAR';
update nfl_games set network = 'ESPN' where week = 4 and away_team = 'ATL' and home_team = 'NO';
update nfl_games set network = 'Prime Video' where week = 5 and away_team = 'TB' and home_team = 'DAL';
update nfl_games set network = 'NFL Net' where week = 5 and away_team = 'PHI' and home_team = 'JAX';
update nfl_games set network = 'CBS' where week = 5 and away_team = 'HOU' and home_team = 'TEN';
update nfl_games set network = 'FOX' where week = 5 and away_team = 'CIN' and home_team = 'MIA';
update nfl_games set network = 'CBS' where week = 5 and away_team = 'LV' and home_team = 'NE';
update nfl_games set network = 'FOX' where week = 5 and away_team = 'MIN' and home_team = 'NO';
update nfl_games set network = 'CBS' where week = 5 and away_team = 'CLE' and home_team = 'NYJ';
update nfl_games set network = 'CBS' where week = 5 and away_team = 'IND' and home_team = 'PIT';
update nfl_games set network = 'FOX' where week = 5 and away_team = 'NYG' and home_team = 'WAS';
update nfl_games set network = 'CBS' where week = 5 and away_team = 'DEN' and home_team = 'LAC';
update nfl_games set network = 'FOX' where week = 5 and away_team = 'CHI' and home_team = 'GB';
update nfl_games set network = 'FOX' where week = 5 and away_team = 'DET' and home_team = 'ARI';
update nfl_games set network = 'FOX' where week = 5 and away_team = 'SF' and home_team = 'SEA';
update nfl_games set network = 'NBC' where week = 5 and away_team = 'BAL' and home_team = 'ATL';
update nfl_games set network = 'ESPN/ABC' where week = 5 and away_team = 'BUF' and home_team = 'LAR';
update nfl_games set network = 'Prime Video' where week = 6 and away_team = 'SEA' and home_team = 'DEN';
update nfl_games set network = 'NFL Net' where week = 6 and away_team = 'HOU' and home_team = 'JAX';
update nfl_games set network = 'FOX' where week = 6 and away_team = 'CHI' and home_team = 'ATL';
update nfl_games set network = 'FOX' where week = 6 and away_team = 'BAL' and home_team = 'CLE';
update nfl_games set network = 'FOX' where week = 6 and away_team = 'TEN' and home_team = 'IND';
update nfl_games set network = 'CBS' where week = 6 and away_team = 'NYJ' and home_team = 'NE';
update nfl_games set network = 'FOX' where week = 6 and away_team = 'NO' and home_team = 'NYG';
update nfl_games set network = 'CBS' where week = 6 and away_team = 'CAR' and home_team = 'PHI';
update nfl_games set network = 'CBS' where week = 6 and away_team = 'PIT' and home_team = 'TB';
update nfl_games set network = 'FOX' where week = 6 and away_team = 'ARI' and home_team = 'LAR';
update nfl_games set network = 'CBS' where week = 6 and away_team = 'LAC' and home_team = 'KC';
update nfl_games set network = 'CBS' where week = 6 and away_team = 'BUF' and home_team = 'LV';
update nfl_games set network = 'NBC' where week = 6 and away_team = 'DAL' and home_team = 'GB';
update nfl_games set network = 'ESPN/ABC' where week = 6 and away_team = 'WAS' and home_team = 'SF';
update nfl_games set network = 'Prime Video' where week = 7 and away_team = 'NE' and home_team = 'CHI';
update nfl_games set network = 'NFL Net' where week = 7 and away_team = 'PIT' and home_team = 'NO';
update nfl_games set network = 'FOX' where week = 7 and away_team = 'SF' and home_team = 'ATL';
update nfl_games set network = 'CBS' where week = 7 and away_team = 'CLE' and home_team = 'TEN';
update nfl_games set network = 'CBS' where week = 7 and away_team = 'IND' and home_team = 'MIN';
update nfl_games set network = 'CBS' where week = 7 and away_team = 'MIA' and home_team = 'NYJ';
update nfl_games set network = 'FOX' where week = 7 and away_team = 'TB' and home_team = 'CAR';
update nfl_games set network = 'CBS' where week = 7 and away_team = 'CIN' and home_team = 'BAL';
update nfl_games set network = 'FOX' where week = 7 and away_team = 'NYG' and home_team = 'HOU';
update nfl_games set network = 'CBS' where week = 7 and away_team = 'DEN' and home_team = 'ARI';
update nfl_games set network = 'FOX' where week = 7 and away_team = 'GB' and home_team = 'DET';
update nfl_games set network = 'FOX' where week = 7 and away_team = 'LAR' and home_team = 'LV';
update nfl_games set network = 'NBC' where week = 7 and away_team = 'KC' and home_team = 'SEA';
update nfl_games set network = 'ESPN/ABC' where week = 7 and away_team = 'DAL' and home_team = 'PHI';
update nfl_games set network = 'Prime Video' where week = 8 and away_team = 'CAR' and home_team = 'GB';
update nfl_games set network = 'CBS' where week = 8 and away_team = 'BAL' and home_team = 'BUF';
update nfl_games set network = 'CBS' where week = 8 and away_team = 'TEN' and home_team = 'CIN';
update nfl_games set network = 'FOX' where week = 8 and away_team = 'ARI' and home_team = 'DAL';
update nfl_games set network = 'FOX' where week = 8 and away_team = 'MIN' and home_team = 'DET';
update nfl_games set network = 'FOX' where week = 8 and away_team = 'LV' and home_team = 'NYJ';
update nfl_games set network = 'CBS' where week = 8 and away_team = 'CLE' and home_team = 'PIT';
update nfl_games set network = 'FOX' where week = 8 and away_team = 'ATL' and home_team = 'TB';
update nfl_games set network = 'CBS' where week = 8 and away_team = 'IND' and home_team = 'JAX';
update nfl_games set network = 'FOX' where week = 8 and away_team = 'LAC' and home_team = 'LAR';
update nfl_games set network = 'CBS' where week = 8 and away_team = 'KC' and home_team = 'DEN';
update nfl_games set network = 'CBS' where week = 8 and away_team = 'NE' and home_team = 'MIA';
update nfl_games set network = 'NBC' where week = 8 and away_team = 'PHI' and home_team = 'WAS';
update nfl_games set network = 'ESPN' where week = 8 and away_team = 'CHI' and home_team = 'SEA';
update nfl_games set network = 'Prime Video' where week = 9 and away_team = 'JAX' and home_team = 'BAL';
update nfl_games set network = 'NFL Net' where week = 9 and away_team = 'CIN' and home_team = 'ATL';
update nfl_games set network = 'FOX' where week = 9 and away_team = 'DAL' and home_team = 'IND';
update nfl_games set network = 'CBS' where week = 9 and away_team = 'NYJ' and home_team = 'KC';
update nfl_games set network = 'FOX' where week = 9 and away_team = 'DET' and home_team = 'MIA';
update nfl_games set network = 'CBS' where week = 9 and away_team = 'CLE' and home_team = 'NO';
update nfl_games set network = 'FOX' where week = 9 and away_team = 'NYG' and home_team = 'PHI';
update nfl_games set network = 'FOX' where week = 9 and away_team = 'LAR' and home_team = 'WAS';
update nfl_games set network = 'CBS' where week = 9 and away_team = 'DEN' and home_team = 'CAR';
update nfl_games set network = 'CBS' where week = 9 and away_team = 'HOU' and home_team = 'LAC';
update nfl_games set network = 'CBS' where week = 9 and away_team = 'LV' and home_team = 'SF';
update nfl_games set network = 'FOX' where week = 9 and away_team = 'GB' and home_team = 'NE';
update nfl_games set network = 'FOX' where week = 9 and away_team = 'ARI' and home_team = 'SEA';
update nfl_games set network = 'NBC' where week = 9 and away_team = 'TB' and home_team = 'CHI';
update nfl_games set network = 'ESPN/ABC' where week = 9 and away_team = 'BUF' and home_team = 'MIN';
update nfl_games set network = 'Prime Video' where week = 10 and away_team = 'WAS' and home_team = 'NYG';
update nfl_games set network = 'FOX' where week = 10 and away_team = 'NE' and home_team = 'DET';
update nfl_games set network = 'CBS' where week = 10 and away_team = 'KC' and home_team = 'ATL';
update nfl_games set network = 'FOX' where week = 10 and away_team = 'HOU' and home_team = 'CLE';
update nfl_games set network = 'FOX' where week = 10 and away_team = 'MIN' and home_team = 'GB';
update nfl_games set network = 'FOX' where week = 10 and away_team = 'JAX' and home_team = 'TEN';
update nfl_games set network = 'CBS' where week = 10 and away_team = 'MIA' and home_team = 'IND';
update nfl_games set network = 'FOX' where week = 10 and away_team = 'CAR' and home_team = 'NO';
update nfl_games set network = 'CBS' where week = 10 and away_team = 'BUF' and home_team = 'NYJ';
update nfl_games set network = 'CBS' where week = 10 and away_team = 'SEA' and home_team = 'LV';
update nfl_games set network = 'CBS' where week = 10 and away_team = 'LAR' and home_team = 'ARI';
update nfl_games set network = 'FOX' where week = 10 and away_team = 'SF' and home_team = 'DAL';
update nfl_games set network = 'NBC' where week = 10 and away_team = 'PIT' and home_team = 'CIN';
update nfl_games set network = 'ESPN' where week = 10 and away_team = 'LAC' and home_team = 'BAL';
update nfl_games set network = 'Prime Video' where week = 11 and away_team = 'IND' and home_team = 'HOU';
update nfl_games set network = 'FOX' where week = 11 and away_team = 'MIA' and home_team = 'BUF';
update nfl_games set network = 'FOX' where week = 11 and away_team = 'NO' and home_team = 'CHI';
update nfl_games set network = 'FOX' where week = 11 and away_team = 'TEN' and home_team = 'DAL';
update nfl_games set network = 'CBS' where week = 11 and away_team = 'TB' and home_team = 'DET';
update nfl_games set network = 'CBS' where week = 11 and away_team = 'ARI' and home_team = 'KC';
update nfl_games set network = 'CBS' where week = 11 and away_team = 'JAX' and home_team = 'NYG';
update nfl_games set network = 'FOX' where week = 11 and away_team = 'BAL' and home_team = 'CAR';
update nfl_games set network = 'FOX' where week = 11 and away_team = 'NYJ' and home_team = 'LAC';
update nfl_games set network = 'CBS' where week = 11 and away_team = 'LV' and home_team = 'DEN';
update nfl_games set network = 'CBS' where week = 11 and away_team = 'PIT' and home_team = 'PHI';
update nfl_games set network = 'NBC' where week = 11 and away_team = 'MIN' and home_team = 'SF';
update nfl_games set network = 'ESPN' where week = 11 and away_team = 'CIN' and home_team = 'WAS';
update nfl_games set network = 'Netflix' where week = 12 and away_team = 'GB' and home_team = 'LAR';
update nfl_games set network = 'CBS' where week = 12 and away_team = 'CHI' and home_team = 'DET';
update nfl_games set network = 'FOX' where week = 12 and away_team = 'PHI' and home_team = 'DAL';
update nfl_games set network = 'NBC' where week = 12 and away_team = 'KC' and home_team = 'BUF';
update nfl_games set network = 'Prime Video' where week = 12 and away_team = 'DEN' and home_team = 'PIT';
update nfl_games set network = 'CBS' where week = 12 and away_team = 'NO' and home_team = 'CIN';
update nfl_games set network = 'FOX' where week = 12 and away_team = 'LV' and home_team = 'CLE';
update nfl_games set network = 'FOX' where week = 12 and away_team = 'NYG' and home_team = 'IND';
update nfl_games set network = 'CBS' where week = 12 and away_team = 'NYJ' and home_team = 'MIA';
update nfl_games set network = 'FOX' where week = 12 and away_team = 'ATL' and home_team = 'MIN';
update nfl_games set network = 'CBS' where week = 12 and away_team = 'BAL' and home_team = 'HOU';
update nfl_games set network = 'CBS' where week = 12 and away_team = 'TEN' and home_team = 'JAX';
update nfl_games set network = 'FOX' where week = 12 and away_team = 'WAS' and home_team = 'ARI';
update nfl_games set network = 'FOX' where week = 12 and away_team = 'SEA' and home_team = 'SF';
update nfl_games set network = 'NBC' where week = 12 and away_team = 'NE' and home_team = 'LAC';
update nfl_games set network = 'ESPN' where week = 12 and away_team = 'CAR' and home_team = 'TB';
update nfl_games set network = 'Prime Video' where week = 13 and away_team = 'KC' and home_team = 'LAR';
update nfl_games set network = 'CBS' where week = 13 and away_team = 'DET' and home_team = 'ATL';
update nfl_games set network = 'FOX' where week = 13 and away_team = 'JAX' and home_team = 'CHI';
update nfl_games set network = 'CBS' where week = 13 and away_team = 'CIN' and home_team = 'CLE';
update nfl_games set network = 'CBS' where week = 13 and away_team = 'WAS' and home_team = 'TEN';
update nfl_games set network = 'FOX' where week = 13 and away_team = 'GB' and home_team = 'NO';
update nfl_games set network = 'FOX' where week = 13 and away_team = 'SF' and home_team = 'NYG';
update nfl_games set network = 'CBS' where week = 13 and away_team = 'LAC' and home_team = 'TB';
update nfl_games set network = 'FOX' where week = 13 and away_team = 'MIA' and home_team = 'DEN';
update nfl_games set network = 'FOX' where week = 13 and away_team = 'PHI' and home_team = 'ARI';
update nfl_games set network = 'CBS' where week = 13 and away_team = 'CAR' and home_team = 'MIN';
update nfl_games set network = 'CBS' where week = 13 and away_team = 'BUF' and home_team = 'NE';
update nfl_games set network = 'NBC' where week = 13 and away_team = 'HOU' and home_team = 'PIT';
update nfl_games set network = 'ESPN/ABC' where week = 13 and away_team = 'DAL' and home_team = 'SEA';
update nfl_games set network = 'Prime Video' where week = 14 and away_team = 'MIN' and home_team = 'NE';
update nfl_games set network = 'CBS' where week = 14 and away_team = 'ATL' and home_team = 'CLE';
update nfl_games set network = 'FOX' where week = 14 and away_team = 'TEN' and home_team = 'DET';
update nfl_games set network = 'CBS' where week = 14 and away_team = 'CHI' and home_team = 'MIA';
update nfl_games set network = 'CBS' where week = 14 and away_team = 'DEN' and home_team = 'NYJ';
update nfl_games set network = 'FOX' where week = 14 and away_team = 'IND' and home_team = 'PHI';
update nfl_games set network = 'CBS' where week = 14 and away_team = 'HOU' and home_team = 'WAS';
update nfl_games set network = 'CBS' where week = 14 and away_team = 'NO' and home_team = 'CAR';
update nfl_games set network = 'FOX' where week = 14 and away_team = 'TB' and home_team = 'BAL';
update nfl_games set network = 'CBS' where week = 14 and away_team = 'LAC' and home_team = 'LV';
update nfl_games set network = 'FOX' where week = 14 and away_team = 'KC' and home_team = 'CIN';
update nfl_games set network = 'FOX' where week = 14 and away_team = 'LAR' and home_team = 'SF';
update nfl_games set network = 'FOX' where week = 14 and away_team = 'NYG' and home_team = 'SEA';
update nfl_games set network = 'NBC' where week = 14 and away_team = 'BUF' and home_team = 'GB';
update nfl_games set network = 'ESPN' where week = 14 and away_team = 'PIT' and home_team = 'JAX';
update nfl_games set network = 'Prime Video' where week = 15 and away_team = 'SF' and home_team = 'LAC';
update nfl_games set network = 'FOX' where week = 15 and away_team = 'SEA' and home_team = 'PHI';
update nfl_games set network = 'CBS' where week = 15 and away_team = 'CHI' and home_team = 'BUF';
update nfl_games set network = 'FOX' where week = 15 and away_team = 'MIA' and home_team = 'GB';
update nfl_games set network = 'CBS' where week = 15 and away_team = 'IND' and home_team = 'TEN';
update nfl_games set network = 'CBS' where week = 15 and away_team = 'CLE' and home_team = 'NYG';
update nfl_games set network = 'CBS' where week = 15 and away_team = 'BAL' and home_team = 'PIT';
update nfl_games set network = 'FOX' where week = 15 and away_team = 'NO' and home_team = 'TB';
update nfl_games set network = 'FOX' where week = 15 and away_team = 'ATL' and home_team = 'WAS';
update nfl_games set network = 'FOX' where week = 15 and away_team = 'CIN' and home_team = 'CAR';
update nfl_games set network = 'CBS' where week = 15 and away_team = 'JAX' and home_team = 'HOU';
update nfl_games set network = 'FOX' where week = 15 and away_team = 'NYJ' and home_team = 'ARI';
update nfl_games set network = 'CBS' where week = 15 and away_team = 'DEN' and home_team = 'LV';
update nfl_games set network = 'CBS' where week = 15 and away_team = 'DAL' and home_team = 'LAR';
update nfl_games set network = 'NBC' where week = 15 and away_team = 'DET' and home_team = 'MIN';
update nfl_games set network = 'ESPN/ABC' where week = 15 and away_team = 'NE' and home_team = 'KC';
update nfl_games set network = 'Prime Video' where week = 16 and away_team = 'HOU' and home_team = 'PHI';
update nfl_games set network = 'Netflix' where week = 16 and away_team = 'GB' and home_team = 'CHI';
update nfl_games set network = 'Netflix' where week = 16 and away_team = 'BUF' and home_team = 'DEN';
update nfl_games set network = 'FOX' where week = 16 and away_team = 'LAR' and home_team = 'SEA';
update nfl_games set network = 'FOX' where week = 16 and away_team = 'LAC' and home_team = 'MIA';
update nfl_games set network = 'FOX' where week = 16 and away_team = 'ARI' and home_team = 'NO';
update nfl_games set network = 'CBS' where week = 16 and away_team = 'NE' and home_team = 'NYJ';
update nfl_games set network = 'CBS' where week = 16 and away_team = 'CLE' and home_team = 'BAL';
update nfl_games set network = 'FOX' where week = 16 and away_team = 'TEN' and home_team = 'LV';
update nfl_games set network = 'CBS' where week = 16 and away_team = 'SF' and home_team = 'KC';
update nfl_games set network = 'NBC' where week = 16 and away_team = 'JAX' and home_team = 'DAL';
update nfl_games set network = 'ESPN' where week = 16 and away_team = 'NYG' and home_team = 'DET';
update nfl_games set network = 'Prime Video' where week = 17 and away_team = 'BAL' and home_team = 'CIN';
update nfl_games set network = 'FOX' where week = 17 and away_team = 'NO' and home_team = 'ATL';
update nfl_games set network = 'FOX' where week = 17 and away_team = 'IND' and home_team = 'CLE';
update nfl_games set network = 'FOX' where week = 17 and away_team = 'NYG' and home_team = 'DAL';
update nfl_games set network = 'CBS' where week = 17 and away_team = 'PIT' and home_team = 'TEN';
update nfl_games set network = 'CBS' where week = 17 and away_team = 'BUF' and home_team = 'MIA';
update nfl_games set network = 'CBS' where week = 17 and away_team = 'MIN' and home_team = 'NYJ';
update nfl_games set network = 'FOX' where week = 17 and away_team = 'SEA' and home_team = 'CAR';
update nfl_games set network = 'CBS' where week = 17 and away_team = 'LV' and home_team = 'ARI';
update nfl_games set network = 'FOX' where week = 17 and away_team = 'DET' and home_team = 'CHI';
update nfl_games set network = 'NBC' where week = 17 and away_team = 'PHI' and home_team = 'SF';
update nfl_games set network = 'ESPN' where week = 17 and away_team = 'HOU' and home_team = 'GB';

do $$
declare n int;
begin
  select count(*) into n from nfl_games where network is not null;
  if n <> 248 then
    raise exception 'expected 248 games with networks, found %', n;
  end if;
end $$;
