-- 2026 NFL regular-season schedule + per-pick deadline windows.
-- GENERATED by scripts/schedule/generate-migration.mjs from nflverse
-- games.csv (github.com/nflverse/nfldata) — verified 272 games, 18 weeks,
-- every team 17 games with one bye. Do not hand-edit the seeded rows;
-- regenerate from a fresh CSV instead.
--
-- Deadline model: a pick's deadline depends on the day its team plays.
--   Wed/Thu/Fri kickoff  -> Wednesday 12:00 PM ET of that game week
--   Sat/Sun/Mon kickoff  -> Friday 12:00 PM ET of that game week
--   Week 1               -> Tuesday 2026-09-08 12:00 PM ET, every pick
-- weeks.deadline_at stays the LATE deadline: the moment the whole week is
-- locked (reveal + sweep boundary). Weeks with schedule-derived windows are
-- auto-confirmed.

create table nfl_games (
  id text primary key,
  week int not null references weeks(week),
  kickoff_at timestamptz not null,
  day_of_week text not null check (day_of_week in
    ('Wednesday','Thursday','Friday','Saturday','Sunday','Monday')),
  away_team text not null,
  home_team text not null,
  source text not null default 'nflverse',
  check (away_team <> home_team)
);
create index nfl_games_week_idx on nfl_games (week);
create index nfl_games_home_idx on nfl_games (week, home_team);
create index nfl_games_away_idx on nfl_games (week, away_team);

alter table nfl_games enable row level security;
create policy "public_read_nfl_games" on nfl_games for select using (true);
grant select on nfl_games to anon, authenticated;

insert into nfl_games (id, week, kickoff_at, day_of_week, away_team, home_team) values
  ('2026_01_NE_SEA', 1, '2026-09-10T00:20:00+00', 'Wednesday', 'NE', 'SEA'),
  ('2026_01_SF_LA', 1, '2026-09-11T00:35:00+00', 'Thursday', 'SF', 'LAR'),
  ('2026_01_ATL_PIT', 1, '2026-09-13T17:00:00+00', 'Sunday', 'ATL', 'PIT'),
  ('2026_01_BAL_IND', 1, '2026-09-13T17:00:00+00', 'Sunday', 'BAL', 'IND'),
  ('2026_01_BUF_HOU', 1, '2026-09-13T17:00:00+00', 'Sunday', 'BUF', 'HOU'),
  ('2026_01_CHI_CAR', 1, '2026-09-13T17:00:00+00', 'Sunday', 'CHI', 'CAR'),
  ('2026_01_CLE_JAX', 1, '2026-09-13T17:00:00+00', 'Sunday', 'CLE', 'JAX'),
  ('2026_01_NO_DET', 1, '2026-09-13T17:00:00+00', 'Sunday', 'NO', 'DET'),
  ('2026_01_NYJ_TEN', 1, '2026-09-13T17:00:00+00', 'Sunday', 'NYJ', 'TEN'),
  ('2026_01_TB_CIN', 1, '2026-09-13T17:00:00+00', 'Sunday', 'TB', 'CIN'),
  ('2026_01_ARI_LAC', 1, '2026-09-13T20:25:00+00', 'Sunday', 'ARI', 'LAC'),
  ('2026_01_GB_MIN', 1, '2026-09-13T20:25:00+00', 'Sunday', 'GB', 'MIN'),
  ('2026_01_MIA_LV', 1, '2026-09-13T20:25:00+00', 'Sunday', 'MIA', 'LV'),
  ('2026_01_WAS_PHI', 1, '2026-09-13T20:25:00+00', 'Sunday', 'WAS', 'PHI'),
  ('2026_01_DAL_NYG', 1, '2026-09-14T00:20:00+00', 'Sunday', 'DAL', 'NYG'),
  ('2026_01_DEN_KC', 1, '2026-09-15T00:15:00+00', 'Monday', 'DEN', 'KC'),
  ('2026_02_DET_BUF', 2, '2026-09-18T00:15:00+00', 'Thursday', 'DET', 'BUF'),
  ('2026_02_CAR_ATL', 2, '2026-09-20T17:00:00+00', 'Sunday', 'CAR', 'ATL'),
  ('2026_02_CIN_HOU', 2, '2026-09-20T17:00:00+00', 'Sunday', 'CIN', 'HOU'),
  ('2026_02_CLE_TB', 2, '2026-09-20T17:00:00+00', 'Sunday', 'CLE', 'TB'),
  ('2026_02_GB_NYJ', 2, '2026-09-20T17:00:00+00', 'Sunday', 'GB', 'NYJ'),
  ('2026_02_MIN_CHI', 2, '2026-09-20T17:00:00+00', 'Sunday', 'MIN', 'CHI'),
  ('2026_02_NO_BAL', 2, '2026-09-20T17:00:00+00', 'Sunday', 'NO', 'BAL'),
  ('2026_02_PHI_TEN', 2, '2026-09-20T17:00:00+00', 'Sunday', 'PHI', 'TEN'),
  ('2026_02_PIT_NE', 2, '2026-09-20T17:00:00+00', 'Sunday', 'PIT', 'NE'),
  ('2026_02_JAX_DEN', 2, '2026-09-20T20:05:00+00', 'Sunday', 'JAX', 'DEN'),
  ('2026_02_LV_LAC', 2, '2026-09-20T20:05:00+00', 'Sunday', 'LV', 'LAC'),
  ('2026_02_MIA_SF', 2, '2026-09-20T20:25:00+00', 'Sunday', 'MIA', 'SF'),
  ('2026_02_SEA_ARI', 2, '2026-09-20T20:25:00+00', 'Sunday', 'SEA', 'ARI'),
  ('2026_02_WAS_DAL', 2, '2026-09-20T20:25:00+00', 'Sunday', 'WAS', 'DAL'),
  ('2026_02_IND_KC', 2, '2026-09-21T00:20:00+00', 'Sunday', 'IND', 'KC'),
  ('2026_02_NYG_LA', 2, '2026-09-22T00:15:00+00', 'Monday', 'NYG', 'LAR'),
  ('2026_03_ATL_GB', 3, '2026-09-25T00:15:00+00', 'Thursday', 'ATL', 'GB'),
  ('2026_03_CAR_CLE', 3, '2026-09-27T17:00:00+00', 'Sunday', 'CAR', 'CLE'),
  ('2026_03_CIN_PIT', 3, '2026-09-27T17:00:00+00', 'Sunday', 'CIN', 'PIT'),
  ('2026_03_HOU_IND', 3, '2026-09-27T17:00:00+00', 'Sunday', 'HOU', 'IND'),
  ('2026_03_KC_MIA', 3, '2026-09-27T17:00:00+00', 'Sunday', 'KC', 'MIA'),
  ('2026_03_LAC_BUF', 3, '2026-09-27T17:00:00+00', 'Sunday', 'LAC', 'BUF'),
  ('2026_03_NE_JAX', 3, '2026-09-27T17:00:00+00', 'Sunday', 'NE', 'JAX'),
  ('2026_03_NYJ_DET', 3, '2026-09-27T17:00:00+00', 'Sunday', 'NYJ', 'DET'),
  ('2026_03_SEA_WAS', 3, '2026-09-27T17:00:00+00', 'Sunday', 'SEA', 'WAS'),
  ('2026_03_TEN_NYG', 3, '2026-09-27T17:00:00+00', 'Sunday', 'TEN', 'NYG'),
  ('2026_03_ARI_SF', 3, '2026-09-27T20:05:00+00', 'Sunday', 'ARI', 'SF'),
  ('2026_03_MIN_TB', 3, '2026-09-27T20:05:00+00', 'Sunday', 'MIN', 'TB'),
  ('2026_03_BAL_DAL', 3, '2026-09-27T20:25:00+00', 'Sunday', 'BAL', 'DAL'),
  ('2026_03_LV_NO', 3, '2026-09-27T20:25:00+00', 'Sunday', 'LV', 'NO'),
  ('2026_03_LA_DEN', 3, '2026-09-28T00:20:00+00', 'Sunday', 'LAR', 'DEN'),
  ('2026_03_PHI_CHI', 3, '2026-09-29T00:15:00+00', 'Monday', 'PHI', 'CHI'),
  ('2026_04_PIT_CLE', 4, '2026-10-02T00:15:00+00', 'Thursday', 'PIT', 'CLE'),
  ('2026_04_IND_WAS', 4, '2026-10-04T13:30:00+00', 'Sunday', 'IND', 'WAS'),
  ('2026_04_ARI_NYG', 4, '2026-10-04T17:00:00+00', 'Sunday', 'ARI', 'NYG'),
  ('2026_04_DAL_HOU', 4, '2026-10-04T17:00:00+00', 'Sunday', 'DAL', 'HOU'),
  ('2026_04_GB_TB', 4, '2026-10-04T17:00:00+00', 'Sunday', 'GB', 'TB'),
  ('2026_04_JAX_CIN', 4, '2026-10-04T17:00:00+00', 'Sunday', 'JAX', 'CIN'),
  ('2026_04_LA_PHI', 4, '2026-10-04T17:00:00+00', 'Sunday', 'LAR', 'PHI'),
  ('2026_04_NE_BUF', 4, '2026-10-04T17:00:00+00', 'Sunday', 'NE', 'BUF'),
  ('2026_04_NYJ_CHI', 4, '2026-10-04T17:00:00+00', 'Sunday', 'NYJ', 'CHI'),
  ('2026_04_TEN_BAL', 4, '2026-10-04T17:00:00+00', 'Sunday', 'TEN', 'BAL'),
  ('2026_04_MIA_MIN', 4, '2026-10-04T20:05:00+00', 'Sunday', 'MIA', 'MIN'),
  ('2026_04_DEN_SF', 4, '2026-10-04T20:25:00+00', 'Sunday', 'DEN', 'SF'),
  ('2026_04_KC_LV', 4, '2026-10-04T20:25:00+00', 'Sunday', 'KC', 'LV'),
  ('2026_04_LAC_SEA', 4, '2026-10-04T20:25:00+00', 'Sunday', 'LAC', 'SEA'),
  ('2026_04_DET_CAR', 4, '2026-10-05T00:20:00+00', 'Sunday', 'DET', 'CAR'),
  ('2026_04_ATL_NO', 4, '2026-10-06T00:15:00+00', 'Monday', 'ATL', 'NO'),
  ('2026_05_TB_DAL', 5, '2026-10-09T00:15:00+00', 'Thursday', 'TB', 'DAL'),
  ('2026_05_PHI_JAX', 5, '2026-10-11T13:30:00+00', 'Sunday', 'PHI', 'JAX'),
  ('2026_05_CIN_MIA', 5, '2026-10-11T17:00:00+00', 'Sunday', 'CIN', 'MIA'),
  ('2026_05_CLE_NYJ', 5, '2026-10-11T17:00:00+00', 'Sunday', 'CLE', 'NYJ'),
  ('2026_05_HOU_TEN', 5, '2026-10-11T17:00:00+00', 'Sunday', 'HOU', 'TEN'),
  ('2026_05_IND_PIT', 5, '2026-10-11T17:00:00+00', 'Sunday', 'IND', 'PIT'),
  ('2026_05_LV_NE', 5, '2026-10-11T17:00:00+00', 'Sunday', 'LV', 'NE'),
  ('2026_05_MIN_NO', 5, '2026-10-11T17:00:00+00', 'Sunday', 'MIN', 'NO'),
  ('2026_05_NYG_WAS', 5, '2026-10-11T17:00:00+00', 'Sunday', 'NYG', 'WAS'),
  ('2026_05_DEN_LAC', 5, '2026-10-11T20:05:00+00', 'Sunday', 'DEN', 'LAC'),
  ('2026_05_CHI_GB', 5, '2026-10-11T20:25:00+00', 'Sunday', 'CHI', 'GB'),
  ('2026_05_DET_ARI', 5, '2026-10-11T20:25:00+00', 'Sunday', 'DET', 'ARI'),
  ('2026_05_SF_SEA', 5, '2026-10-11T20:25:00+00', 'Sunday', 'SF', 'SEA'),
  ('2026_05_BAL_ATL', 5, '2026-10-12T00:20:00+00', 'Sunday', 'BAL', 'ATL'),
  ('2026_05_BUF_LA', 5, '2026-10-13T00:15:00+00', 'Monday', 'BUF', 'LAR'),
  ('2026_06_SEA_DEN', 6, '2026-10-16T00:15:00+00', 'Thursday', 'SEA', 'DEN'),
  ('2026_06_HOU_JAX', 6, '2026-10-18T13:30:00+00', 'Sunday', 'HOU', 'JAX'),
  ('2026_06_BAL_CLE', 6, '2026-10-18T17:00:00+00', 'Sunday', 'BAL', 'CLE'),
  ('2026_06_CAR_PHI', 6, '2026-10-18T17:00:00+00', 'Sunday', 'CAR', 'PHI'),
  ('2026_06_CHI_ATL', 6, '2026-10-18T17:00:00+00', 'Sunday', 'CHI', 'ATL'),
  ('2026_06_NO_NYG', 6, '2026-10-18T17:00:00+00', 'Sunday', 'NO', 'NYG'),
  ('2026_06_NYJ_NE', 6, '2026-10-18T17:00:00+00', 'Sunday', 'NYJ', 'NE'),
  ('2026_06_PIT_TB', 6, '2026-10-18T17:00:00+00', 'Sunday', 'PIT', 'TB'),
  ('2026_06_TEN_IND', 6, '2026-10-18T17:00:00+00', 'Sunday', 'TEN', 'IND'),
  ('2026_06_ARI_LA', 6, '2026-10-18T20:05:00+00', 'Sunday', 'ARI', 'LAR'),
  ('2026_06_BUF_LV', 6, '2026-10-18T20:25:00+00', 'Sunday', 'BUF', 'LV'),
  ('2026_06_LAC_KC', 6, '2026-10-18T20:25:00+00', 'Sunday', 'LAC', 'KC'),
  ('2026_06_DAL_GB', 6, '2026-10-19T00:20:00+00', 'Sunday', 'DAL', 'GB'),
  ('2026_06_WAS_SF', 6, '2026-10-20T00:15:00+00', 'Monday', 'WAS', 'SF'),
  ('2026_07_NE_CHI', 7, '2026-10-23T00:15:00+00', 'Thursday', 'NE', 'CHI'),
  ('2026_07_PIT_NO', 7, '2026-10-25T13:30:00+00', 'Sunday', 'PIT', 'NO'),
  ('2026_07_CIN_BAL', 7, '2026-10-25T17:00:00+00', 'Sunday', 'CIN', 'BAL'),
  ('2026_07_CLE_TEN', 7, '2026-10-25T17:00:00+00', 'Sunday', 'CLE', 'TEN'),
  ('2026_07_IND_MIN', 7, '2026-10-25T17:00:00+00', 'Sunday', 'IND', 'MIN'),
  ('2026_07_MIA_NYJ', 7, '2026-10-25T17:00:00+00', 'Sunday', 'MIA', 'NYJ'),
  ('2026_07_NYG_HOU', 7, '2026-10-25T17:00:00+00', 'Sunday', 'NYG', 'HOU'),
  ('2026_07_SF_ATL', 7, '2026-10-25T17:00:00+00', 'Sunday', 'SF', 'ATL'),
  ('2026_07_TB_CAR', 7, '2026-10-25T17:00:00+00', 'Sunday', 'TB', 'CAR'),
  ('2026_07_DEN_ARI', 7, '2026-10-25T20:05:00+00', 'Sunday', 'DEN', 'ARI'),
  ('2026_07_GB_DET', 7, '2026-10-25T20:25:00+00', 'Sunday', 'GB', 'DET'),
  ('2026_07_LA_LV', 7, '2026-10-25T20:25:00+00', 'Sunday', 'LAR', 'LV'),
  ('2026_07_KC_SEA', 7, '2026-10-26T00:20:00+00', 'Sunday', 'KC', 'SEA'),
  ('2026_07_DAL_PHI', 7, '2026-10-27T00:15:00+00', 'Monday', 'DAL', 'PHI'),
  ('2026_08_CAR_GB', 8, '2026-10-30T00:15:00+00', 'Thursday', 'CAR', 'GB'),
  ('2026_08_ARI_DAL', 8, '2026-11-01T18:00:00+00', 'Sunday', 'ARI', 'DAL'),
  ('2026_08_ATL_TB', 8, '2026-11-01T18:00:00+00', 'Sunday', 'ATL', 'TB'),
  ('2026_08_BAL_BUF', 8, '2026-11-01T18:00:00+00', 'Sunday', 'BAL', 'BUF'),
  ('2026_08_CLE_PIT', 8, '2026-11-01T18:00:00+00', 'Sunday', 'CLE', 'PIT'),
  ('2026_08_IND_JAX', 8, '2026-11-01T18:00:00+00', 'Sunday', 'IND', 'JAX'),
  ('2026_08_LV_NYJ', 8, '2026-11-01T18:00:00+00', 'Sunday', 'LV', 'NYJ'),
  ('2026_08_MIN_DET', 8, '2026-11-01T18:00:00+00', 'Sunday', 'MIN', 'DET'),
  ('2026_08_TEN_CIN', 8, '2026-11-01T18:00:00+00', 'Sunday', 'TEN', 'CIN'),
  ('2026_08_LAC_LA', 8, '2026-11-01T21:05:00+00', 'Sunday', 'LAC', 'LAR'),
  ('2026_08_KC_DEN', 8, '2026-11-01T21:25:00+00', 'Sunday', 'KC', 'DEN'),
  ('2026_08_NE_MIA', 8, '2026-11-01T21:25:00+00', 'Sunday', 'NE', 'MIA'),
  ('2026_08_PHI_WAS', 8, '2026-11-02T01:20:00+00', 'Sunday', 'PHI', 'WAS'),
  ('2026_08_CHI_SEA', 8, '2026-11-03T01:15:00+00', 'Monday', 'CHI', 'SEA'),
  ('2026_09_JAX_BAL', 9, '2026-11-06T01:15:00+00', 'Thursday', 'JAX', 'BAL'),
  ('2026_09_CIN_ATL', 9, '2026-11-08T14:30:00+00', 'Sunday', 'CIN', 'ATL'),
  ('2026_09_CLE_NO', 9, '2026-11-08T18:00:00+00', 'Sunday', 'CLE', 'NO'),
  ('2026_09_DAL_IND', 9, '2026-11-08T18:00:00+00', 'Sunday', 'DAL', 'IND'),
  ('2026_09_DEN_CAR', 9, '2026-11-08T18:00:00+00', 'Sunday', 'DEN', 'CAR'),
  ('2026_09_DET_MIA', 9, '2026-11-08T18:00:00+00', 'Sunday', 'DET', 'MIA'),
  ('2026_09_LA_WAS', 9, '2026-11-08T18:00:00+00', 'Sunday', 'LAR', 'WAS'),
  ('2026_09_NYG_PHI', 9, '2026-11-08T18:00:00+00', 'Sunday', 'NYG', 'PHI'),
  ('2026_09_NYJ_KC', 9, '2026-11-08T18:00:00+00', 'Sunday', 'NYJ', 'KC'),
  ('2026_09_HOU_LAC', 9, '2026-11-08T21:05:00+00', 'Sunday', 'HOU', 'LAC'),
  ('2026_09_LV_SF', 9, '2026-11-08T21:05:00+00', 'Sunday', 'LV', 'SF'),
  ('2026_09_ARI_SEA', 9, '2026-11-08T21:25:00+00', 'Sunday', 'ARI', 'SEA'),
  ('2026_09_GB_NE', 9, '2026-11-08T21:25:00+00', 'Sunday', 'GB', 'NE'),
  ('2026_09_TB_CHI', 9, '2026-11-09T01:20:00+00', 'Sunday', 'TB', 'CHI'),
  ('2026_09_BUF_MIN', 9, '2026-11-10T01:15:00+00', 'Monday', 'BUF', 'MIN'),
  ('2026_10_WAS_NYG', 10, '2026-11-13T01:15:00+00', 'Thursday', 'WAS', 'NYG'),
  ('2026_10_NE_DET', 10, '2026-11-15T14:30:00+00', 'Sunday', 'NE', 'DET'),
  ('2026_10_BUF_NYJ', 10, '2026-11-15T18:00:00+00', 'Sunday', 'BUF', 'NYJ'),
  ('2026_10_CAR_NO', 10, '2026-11-15T18:00:00+00', 'Sunday', 'CAR', 'NO'),
  ('2026_10_HOU_CLE', 10, '2026-11-15T18:00:00+00', 'Sunday', 'HOU', 'CLE'),
  ('2026_10_JAX_TEN', 10, '2026-11-15T18:00:00+00', 'Sunday', 'JAX', 'TEN'),
  ('2026_10_KC_ATL', 10, '2026-11-15T18:00:00+00', 'Sunday', 'KC', 'ATL'),
  ('2026_10_MIA_IND', 10, '2026-11-15T18:00:00+00', 'Sunday', 'MIA', 'IND'),
  ('2026_10_MIN_GB', 10, '2026-11-15T18:00:00+00', 'Sunday', 'MIN', 'GB'),
  ('2026_10_LA_ARI', 10, '2026-11-15T21:05:00+00', 'Sunday', 'LAR', 'ARI'),
  ('2026_10_SEA_LV', 10, '2026-11-15T21:05:00+00', 'Sunday', 'SEA', 'LV'),
  ('2026_10_SF_DAL', 10, '2026-11-15T21:25:00+00', 'Sunday', 'SF', 'DAL'),
  ('2026_10_PIT_CIN', 10, '2026-11-16T01:20:00+00', 'Sunday', 'PIT', 'CIN'),
  ('2026_10_LAC_BAL', 10, '2026-11-17T01:15:00+00', 'Monday', 'LAC', 'BAL'),
  ('2026_11_IND_HOU', 11, '2026-11-20T01:15:00+00', 'Thursday', 'IND', 'HOU'),
  ('2026_11_ARI_KC', 11, '2026-11-22T18:00:00+00', 'Sunday', 'ARI', 'KC'),
  ('2026_11_BAL_CAR', 11, '2026-11-22T18:00:00+00', 'Sunday', 'BAL', 'CAR'),
  ('2026_11_JAX_NYG', 11, '2026-11-22T18:00:00+00', 'Sunday', 'JAX', 'NYG'),
  ('2026_11_MIA_BUF', 11, '2026-11-22T18:00:00+00', 'Sunday', 'MIA', 'BUF'),
  ('2026_11_NO_CHI', 11, '2026-11-22T18:00:00+00', 'Sunday', 'NO', 'CHI'),
  ('2026_11_TB_DET', 11, '2026-11-22T18:00:00+00', 'Sunday', 'TB', 'DET'),
  ('2026_11_TEN_DAL', 11, '2026-11-22T18:00:00+00', 'Sunday', 'TEN', 'DAL'),
  ('2026_11_NYJ_LAC', 11, '2026-11-22T21:05:00+00', 'Sunday', 'NYJ', 'LAC'),
  ('2026_11_LV_DEN', 11, '2026-11-22T21:25:00+00', 'Sunday', 'LV', 'DEN'),
  ('2026_11_PIT_PHI', 11, '2026-11-22T21:25:00+00', 'Sunday', 'PIT', 'PHI'),
  ('2026_11_MIN_SF', 11, '2026-11-23T01:20:00+00', 'Sunday', 'MIN', 'SF'),
  ('2026_11_CIN_WAS', 11, '2026-11-24T01:15:00+00', 'Monday', 'CIN', 'WAS'),
  ('2026_12_GB_LA', 12, '2026-11-26T01:00:00+00', 'Wednesday', 'GB', 'LAR'),
  ('2026_12_CHI_DET', 12, '2026-11-26T18:00:00+00', 'Thursday', 'CHI', 'DET'),
  ('2026_12_PHI_DAL', 12, '2026-11-26T21:30:00+00', 'Thursday', 'PHI', 'DAL'),
  ('2026_12_KC_BUF', 12, '2026-11-27T01:20:00+00', 'Thursday', 'KC', 'BUF'),
  ('2026_12_DEN_PIT', 12, '2026-11-27T20:00:00+00', 'Friday', 'DEN', 'PIT'),
  ('2026_12_ATL_MIN', 12, '2026-11-29T18:00:00+00', 'Sunday', 'ATL', 'MIN'),
  ('2026_12_BAL_HOU', 12, '2026-11-29T18:00:00+00', 'Sunday', 'BAL', 'HOU'),
  ('2026_12_LV_CLE', 12, '2026-11-29T18:00:00+00', 'Sunday', 'LV', 'CLE'),
  ('2026_12_NO_CIN', 12, '2026-11-29T18:00:00+00', 'Sunday', 'NO', 'CIN'),
  ('2026_12_NYG_IND', 12, '2026-11-29T18:00:00+00', 'Sunday', 'NYG', 'IND'),
  ('2026_12_NYJ_MIA', 12, '2026-11-29T18:00:00+00', 'Sunday', 'NYJ', 'MIA'),
  ('2026_12_TEN_JAX', 12, '2026-11-29T21:05:00+00', 'Sunday', 'TEN', 'JAX'),
  ('2026_12_SEA_SF', 12, '2026-11-29T21:25:00+00', 'Sunday', 'SEA', 'SF'),
  ('2026_12_WAS_ARI', 12, '2026-11-29T21:25:00+00', 'Sunday', 'WAS', 'ARI'),
  ('2026_12_NE_LAC', 12, '2026-11-30T01:20:00+00', 'Sunday', 'NE', 'LAC'),
  ('2026_12_CAR_TB', 12, '2026-12-01T01:15:00+00', 'Monday', 'CAR', 'TB'),
  ('2026_13_KC_LA', 13, '2026-12-04T01:15:00+00', 'Thursday', 'KC', 'LAR'),
  ('2026_13_CIN_CLE', 13, '2026-12-06T18:00:00+00', 'Sunday', 'CIN', 'CLE'),
  ('2026_13_DET_ATL', 13, '2026-12-06T18:00:00+00', 'Sunday', 'DET', 'ATL'),
  ('2026_13_GB_NO', 13, '2026-12-06T18:00:00+00', 'Sunday', 'GB', 'NO'),
  ('2026_13_JAX_CHI', 13, '2026-12-06T18:00:00+00', 'Sunday', 'JAX', 'CHI'),
  ('2026_13_LAC_TB', 13, '2026-12-06T18:00:00+00', 'Sunday', 'LAC', 'TB'),
  ('2026_13_SF_NYG', 13, '2026-12-06T18:00:00+00', 'Sunday', 'SF', 'NYG'),
  ('2026_13_WAS_TEN', 13, '2026-12-06T18:00:00+00', 'Sunday', 'WAS', 'TEN'),
  ('2026_13_MIA_DEN', 13, '2026-12-06T21:05:00+00', 'Sunday', 'MIA', 'DEN'),
  ('2026_13_PHI_ARI', 13, '2026-12-06T21:05:00+00', 'Sunday', 'PHI', 'ARI'),
  ('2026_13_BUF_NE', 13, '2026-12-06T21:25:00+00', 'Sunday', 'BUF', 'NE'),
  ('2026_13_CAR_MIN', 13, '2026-12-06T21:25:00+00', 'Sunday', 'CAR', 'MIN'),
  ('2026_13_HOU_PIT', 13, '2026-12-07T01:20:00+00', 'Sunday', 'HOU', 'PIT'),
  ('2026_13_DAL_SEA', 13, '2026-12-08T01:15:00+00', 'Monday', 'DAL', 'SEA'),
  ('2026_14_MIN_NE', 14, '2026-12-11T01:15:00+00', 'Thursday', 'MIN', 'NE'),
  ('2026_14_ATL_CLE', 14, '2026-12-13T18:00:00+00', 'Sunday', 'ATL', 'CLE'),
  ('2026_14_CHI_MIA', 14, '2026-12-13T18:00:00+00', 'Sunday', 'CHI', 'MIA'),
  ('2026_14_DEN_NYJ', 14, '2026-12-13T18:00:00+00', 'Sunday', 'DEN', 'NYJ'),
  ('2026_14_HOU_WAS', 14, '2026-12-13T18:00:00+00', 'Sunday', 'HOU', 'WAS'),
  ('2026_14_IND_PHI', 14, '2026-12-13T18:00:00+00', 'Sunday', 'IND', 'PHI'),
  ('2026_14_NO_CAR', 14, '2026-12-13T18:00:00+00', 'Sunday', 'NO', 'CAR'),
  ('2026_14_TB_BAL', 14, '2026-12-13T18:00:00+00', 'Sunday', 'TB', 'BAL'),
  ('2026_14_TEN_DET', 14, '2026-12-13T18:00:00+00', 'Sunday', 'TEN', 'DET'),
  ('2026_14_LAC_LV', 14, '2026-12-13T21:05:00+00', 'Sunday', 'LAC', 'LV'),
  ('2026_14_KC_CIN', 14, '2026-12-13T21:25:00+00', 'Sunday', 'KC', 'CIN'),
  ('2026_14_LA_SF', 14, '2026-12-13T21:25:00+00', 'Sunday', 'LAR', 'SF'),
  ('2026_14_NYG_SEA', 14, '2026-12-13T21:25:00+00', 'Sunday', 'NYG', 'SEA'),
  ('2026_14_BUF_GB', 14, '2026-12-14T01:20:00+00', 'Sunday', 'BUF', 'GB'),
  ('2026_14_PIT_JAX', 14, '2026-12-15T01:15:00+00', 'Monday', 'PIT', 'JAX'),
  ('2026_15_SF_LAC', 15, '2026-12-18T01:15:00+00', 'Thursday', 'SF', 'LAC'),
  ('2026_15_SEA_PHI', 15, '2026-12-19T22:00:00+00', 'Saturday', 'SEA', 'PHI'),
  ('2026_15_CHI_BUF', 15, '2026-12-20T01:20:00+00', 'Saturday', 'CHI', 'BUF'),
  ('2026_15_ATL_WAS', 15, '2026-12-20T18:00:00+00', 'Sunday', 'ATL', 'WAS'),
  ('2026_15_BAL_PIT', 15, '2026-12-20T18:00:00+00', 'Sunday', 'BAL', 'PIT'),
  ('2026_15_CIN_CAR', 15, '2026-12-20T18:00:00+00', 'Sunday', 'CIN', 'CAR'),
  ('2026_15_CLE_NYG', 15, '2026-12-20T18:00:00+00', 'Sunday', 'CLE', 'NYG'),
  ('2026_15_IND_TEN', 15, '2026-12-20T18:00:00+00', 'Sunday', 'IND', 'TEN'),
  ('2026_15_JAX_HOU', 15, '2026-12-20T18:00:00+00', 'Sunday', 'JAX', 'HOU'),
  ('2026_15_MIA_GB', 15, '2026-12-20T18:00:00+00', 'Sunday', 'MIA', 'GB'),
  ('2026_15_NO_TB', 15, '2026-12-20T18:00:00+00', 'Sunday', 'NO', 'TB'),
  ('2026_15_NYJ_ARI', 15, '2026-12-20T21:05:00+00', 'Sunday', 'NYJ', 'ARI'),
  ('2026_15_DAL_LA', 15, '2026-12-20T21:25:00+00', 'Sunday', 'DAL', 'LAR'),
  ('2026_15_DEN_LV', 15, '2026-12-20T21:25:00+00', 'Sunday', 'DEN', 'LV'),
  ('2026_15_DET_MIN', 15, '2026-12-21T01:20:00+00', 'Sunday', 'DET', 'MIN'),
  ('2026_15_NE_KC', 15, '2026-12-22T01:15:00+00', 'Monday', 'NE', 'KC'),
  ('2026_16_HOU_PHI', 16, '2026-12-25T01:15:00+00', 'Thursday', 'HOU', 'PHI'),
  ('2026_16_GB_CHI', 16, '2026-12-25T18:00:00+00', 'Friday', 'GB', 'CHI'),
  ('2026_16_BUF_DEN', 16, '2026-12-25T21:30:00+00', 'Friday', 'BUF', 'DEN'),
  ('2026_16_LA_SEA', 16, '2026-12-26T01:15:00+00', 'Friday', 'LAR', 'SEA'),
  ('2026_16_ARI_NO', 16, '2026-12-27T18:00:00+00', 'Sunday', 'ARI', 'NO'),
  ('2026_16_CAR_PIT', 16, '2026-12-27T18:00:00+00', 'Sunday', 'CAR', 'PIT'),
  ('2026_16_CIN_IND', 16, '2026-12-27T18:00:00+00', 'Sunday', 'CIN', 'IND'),
  ('2026_16_CLE_BAL', 16, '2026-12-27T18:00:00+00', 'Sunday', 'CLE', 'BAL'),
  ('2026_16_LAC_MIA', 16, '2026-12-27T18:00:00+00', 'Sunday', 'LAC', 'MIA'),
  ('2026_16_NE_NYJ', 16, '2026-12-27T18:00:00+00', 'Sunday', 'NE', 'NYJ'),
  ('2026_16_TB_ATL', 16, '2026-12-27T18:00:00+00', 'Sunday', 'TB', 'ATL'),
  ('2026_16_WAS_MIN', 16, '2026-12-27T18:00:00+00', 'Sunday', 'WAS', 'MIN'),
  ('2026_16_TEN_LV', 16, '2026-12-27T21:05:00+00', 'Sunday', 'TEN', 'LV'),
  ('2026_16_SF_KC', 16, '2026-12-27T21:25:00+00', 'Sunday', 'SF', 'KC'),
  ('2026_16_JAX_DAL', 16, '2026-12-28T01:20:00+00', 'Sunday', 'JAX', 'DAL'),
  ('2026_16_NYG_DET', 16, '2026-12-29T01:15:00+00', 'Monday', 'NYG', 'DET'),
  ('2026_17_BAL_CIN', 17, '2027-01-01T01:15:00+00', 'Thursday', 'BAL', 'CIN'),
  ('2026_17_BUF_MIA', 17, '2027-01-03T18:00:00+00', 'Sunday', 'BUF', 'MIA'),
  ('2026_17_DEN_NE', 17, '2027-01-03T18:00:00+00', 'Sunday', 'DEN', 'NE'),
  ('2026_17_IND_CLE', 17, '2027-01-03T18:00:00+00', 'Sunday', 'IND', 'CLE'),
  ('2026_17_KC_LAC', 17, '2027-01-03T18:00:00+00', 'Sunday', 'KC', 'LAC'),
  ('2026_17_LA_TB', 17, '2027-01-03T18:00:00+00', 'Sunday', 'LAR', 'TB'),
  ('2026_17_MIN_NYJ', 17, '2027-01-03T18:00:00+00', 'Sunday', 'MIN', 'NYJ'),
  ('2026_17_NO_ATL', 17, '2027-01-03T18:00:00+00', 'Sunday', 'NO', 'ATL'),
  ('2026_17_NYG_DAL', 17, '2027-01-03T18:00:00+00', 'Sunday', 'NYG', 'DAL'),
  ('2026_17_PIT_TEN', 17, '2027-01-03T18:00:00+00', 'Sunday', 'PIT', 'TEN'),
  ('2026_17_SEA_CAR', 17, '2027-01-03T18:00:00+00', 'Sunday', 'SEA', 'CAR'),
  ('2026_17_WAS_JAX', 17, '2027-01-03T18:00:00+00', 'Sunday', 'WAS', 'JAX'),
  ('2026_17_LV_ARI', 17, '2027-01-03T21:05:00+00', 'Sunday', 'LV', 'ARI'),
  ('2026_17_DET_CHI', 17, '2027-01-03T21:25:00+00', 'Sunday', 'DET', 'CHI'),
  ('2026_17_PHI_SF', 17, '2027-01-04T01:20:00+00', 'Sunday', 'PHI', 'SF'),
  ('2026_17_HOU_GB', 17, '2027-01-05T01:15:00+00', 'Monday', 'HOU', 'GB'),
  ('2026_18_ATL_CAR', 18, '2027-01-10T18:00:00+00', 'Sunday', 'ATL', 'CAR'),
  ('2026_18_CHI_MIN', 18, '2027-01-10T18:00:00+00', 'Sunday', 'CHI', 'MIN'),
  ('2026_18_CLE_CIN', 18, '2027-01-10T18:00:00+00', 'Sunday', 'CLE', 'CIN'),
  ('2026_18_DAL_WAS', 18, '2027-01-10T18:00:00+00', 'Sunday', 'DAL', 'WAS'),
  ('2026_18_DET_GB', 18, '2027-01-10T18:00:00+00', 'Sunday', 'DET', 'GB'),
  ('2026_18_JAX_IND', 18, '2027-01-10T18:00:00+00', 'Sunday', 'JAX', 'IND'),
  ('2026_18_LAC_DEN', 18, '2027-01-10T18:00:00+00', 'Sunday', 'LAC', 'DEN'),
  ('2026_18_LV_KC', 18, '2027-01-10T18:00:00+00', 'Sunday', 'LV', 'KC'),
  ('2026_18_MIA_NE', 18, '2027-01-10T18:00:00+00', 'Sunday', 'MIA', 'NE'),
  ('2026_18_NYJ_BUF', 18, '2027-01-10T18:00:00+00', 'Sunday', 'NYJ', 'BUF'),
  ('2026_18_PHI_NYG', 18, '2027-01-10T18:00:00+00', 'Sunday', 'PHI', 'NYG'),
  ('2026_18_PIT_BAL', 18, '2027-01-10T18:00:00+00', 'Sunday', 'PIT', 'BAL'),
  ('2026_18_SEA_LA', 18, '2027-01-10T18:00:00+00', 'Sunday', 'SEA', 'LAR'),
  ('2026_18_SF_ARI', 18, '2027-01-10T18:00:00+00', 'Sunday', 'SF', 'ARI'),
  ('2026_18_TB_NO', 18, '2027-01-10T18:00:00+00', 'Sunday', 'TB', 'NO'),
  ('2026_18_TEN_HOU', 18, '2027-01-10T18:00:00+00', 'Sunday', 'TEN', 'HOU');

-- Two windows per week; deadline_at remains the late (full-lock) boundary.
alter table weeks add column early_deadline_at timestamptz;
alter table weeks add column late_deadline_at timestamptz;

update weeks set early_deadline_at = '2026-09-08T16:00:00+00', late_deadline_at = '2026-09-08T16:00:00+00', deadline_at = '2026-09-08T16:00:00+00', confirmed = true where week = 1;
update weeks set early_deadline_at = '2026-09-16T16:00:00+00', late_deadline_at = '2026-09-18T16:00:00+00', deadline_at = '2026-09-18T16:00:00+00', confirmed = true where week = 2;
update weeks set early_deadline_at = '2026-09-23T16:00:00+00', late_deadline_at = '2026-09-25T16:00:00+00', deadline_at = '2026-09-25T16:00:00+00', confirmed = true where week = 3;
update weeks set early_deadline_at = '2026-09-30T16:00:00+00', late_deadline_at = '2026-10-02T16:00:00+00', deadline_at = '2026-10-02T16:00:00+00', confirmed = true where week = 4;
update weeks set early_deadline_at = '2026-10-07T16:00:00+00', late_deadline_at = '2026-10-09T16:00:00+00', deadline_at = '2026-10-09T16:00:00+00', confirmed = true where week = 5;
update weeks set early_deadline_at = '2026-10-14T16:00:00+00', late_deadline_at = '2026-10-16T16:00:00+00', deadline_at = '2026-10-16T16:00:00+00', confirmed = true where week = 6;
update weeks set early_deadline_at = '2026-10-21T16:00:00+00', late_deadline_at = '2026-10-23T16:00:00+00', deadline_at = '2026-10-23T16:00:00+00', confirmed = true where week = 7;
update weeks set early_deadline_at = '2026-10-28T16:00:00+00', late_deadline_at = '2026-10-30T16:00:00+00', deadline_at = '2026-10-30T16:00:00+00', confirmed = true where week = 8;
update weeks set early_deadline_at = '2026-11-04T17:00:00+00', late_deadline_at = '2026-11-06T17:00:00+00', deadline_at = '2026-11-06T17:00:00+00', confirmed = true where week = 9;
update weeks set early_deadline_at = '2026-11-11T17:00:00+00', late_deadline_at = '2026-11-13T17:00:00+00', deadline_at = '2026-11-13T17:00:00+00', confirmed = true where week = 10;
update weeks set early_deadline_at = '2026-11-18T17:00:00+00', late_deadline_at = '2026-11-20T17:00:00+00', deadline_at = '2026-11-20T17:00:00+00', confirmed = true where week = 11;
update weeks set early_deadline_at = '2026-11-25T17:00:00+00', late_deadline_at = '2026-11-27T17:00:00+00', deadline_at = '2026-11-27T17:00:00+00', confirmed = true where week = 12;
update weeks set early_deadline_at = '2026-12-02T17:00:00+00', late_deadline_at = '2026-12-04T17:00:00+00', deadline_at = '2026-12-04T17:00:00+00', confirmed = true where week = 13;
update weeks set early_deadline_at = '2026-12-09T17:00:00+00', late_deadline_at = '2026-12-11T17:00:00+00', deadline_at = '2026-12-11T17:00:00+00', confirmed = true where week = 14;
update weeks set early_deadline_at = '2026-12-16T17:00:00+00', late_deadline_at = '2026-12-18T17:00:00+00', deadline_at = '2026-12-18T17:00:00+00', confirmed = true where week = 15;
update weeks set early_deadline_at = '2026-12-23T17:00:00+00', late_deadline_at = '2026-12-25T17:00:00+00', deadline_at = '2026-12-25T17:00:00+00', confirmed = true where week = 16;
update weeks set early_deadline_at = '2026-12-30T17:00:00+00', late_deadline_at = '2027-01-01T17:00:00+00', deadline_at = '2027-01-01T17:00:00+00', confirmed = true where week = 17;
update weeks set early_deadline_at = '2027-01-06T17:00:00+00', late_deadline_at = '2027-01-08T17:00:00+00', deadline_at = '2027-01-08T17:00:00+00', confirmed = true where week = 18;

alter table weeks alter column early_deadline_at set not null;
alter table weeks alter column late_deadline_at set not null;

-- The deadline for one pick: which window applies depends on the day the
-- picked team plays that week. A bye/unknown team (including SKIP_WEEK)
-- gets the late deadline — the week's final submission boundary.
create or replace function pick_deadline(p_week int, p_team text)
returns timestamptz
language sql
stable
set search_path = public, pg_temp
as $$
  select case
    when w.week = 1 then w.early_deadline_at
    when g.day_of_week in ('Wednesday','Thursday','Friday') then w.early_deadline_at
    else w.late_deadline_at
  end
  from weeks w
  left join nfl_games g
    on g.week = w.week and (g.home_team = p_team or g.away_team = p_team)
  where w.week = p_week
$$;

-- Late flag now derives from the pick's own deadline, not the week's.
-- The bye guards from the rules engine stay exactly as they were.
create or replace function admin_submit_pick(
  p_entry_id uuid,
  p_week int,
  p_team text,
  p_source text,
  p_actor text
) returns uuid
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_deadline timestamptz;
  v_old_id uuid;
  v_new_id uuid;
  v_double_through int;
  v_losses int;
  v_bye_used boolean;
begin
  select pick_deadline(p_week, p_team) into v_deadline;
  if v_deadline is null then
    raise exception 'week % does not exist', p_week;
  end if;

  if p_team = 'SKIP_WEEK' then
    select double_elim_through_week into v_double_through from config;
    if p_week <= v_double_through then
      raise exception 'bye may only be used from week % on', v_double_through + 1;
    end if;
    select count(*) filter (where p.result in ('loss','tie_loss','missed') and p.week <= v_double_through),
           bool_or(p.team = 'SKIP_WEEK')
      into v_losses, v_bye_used
      from picks p
     where p.entry_id = p_entry_id and p.is_current;
    if coalesce(v_losses, 0) > 0 then
      raise exception 'bye not earned: entry took a loss in weeks 1-%', v_double_through;
    end if;
    if coalesce(v_bye_used, false) then
      raise exception 'bye already used';
    end if;
  end if;

  select id into v_old_id from picks
   where entry_id = p_entry_id and week = p_week and is_current;

  if v_old_id is not null then
    update picks set is_current = false where id = v_old_id;
  end if;

  insert into picks (entry_id, week, team, source, supersedes_id, late, result)
  values (p_entry_id, p_week, p_team,
          coalesce(nullif(p_source, ''), 'admin'),
          v_old_id,
          now() > v_deadline,
          case when p_team = 'SKIP_WEEK' then 'bye' else 'pending' end)
  returning id into v_new_id;

  insert into audit_log (actor, action, target_table, target_id, after)
  values (p_actor,
          case when v_old_id is null then 'submit_pick' else 'override_pick' end,
          'picks', v_new_id::text,
          jsonb_build_object('entry_id', p_entry_id, 'week', p_week,
                             'team', p_team, 'supersedes', v_old_id));
  return v_new_id;
end $$;

-- The sweep waits for the LATE deadline: an entry without a pick could
-- still legally submit a Sat-Mon team until Friday noon.
create or replace function admin_deadline_sweep(
  p_week int,
  p_commit boolean,
  p_actor text
) returns table (entry_id uuid, entry_name text, owner_name text)
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_deadline timestamptz;
  v_confirmed boolean;
  v_count int := 0;
  r record;
begin
  select w.late_deadline_at, w.confirmed into v_deadline, v_confirmed
    from weeks w where w.week = p_week;
  if v_deadline is null then
    raise exception 'week % does not exist', p_week;
  end if;
  if p_commit and not v_confirmed then
    raise exception 'week % deadline is not confirmed — confirm it on the Weeks screen before sweeping', p_week;
  end if;
  if p_commit and now() <= v_deadline then
    raise exception 'week % late deadline has not passed; sweep cannot commit', p_week;
  end if;

  drop table if exists _sweep;
  create temp table _sweep on commit drop as
  select e.id as entry_id,
         e.entry_name,
         o.first_name || ' ' || o.last_name as owner_name
  from entries e
  join owners o on o.id = e.owner_id
  join v_entry_standing s on s.entry_id = e.id
  where o.participation_status = 'confirmed'
    and e.voided_at is null
    and s.status <> 'eliminated'
    and not exists (
      select 1 from picks p
      where p.entry_id = e.id and p.week = p_week and p.is_current
    );

  if p_commit then
    for r in select * from _sweep loop
      insert into picks (entry_id, week, team, source, late, result, result_source, submitted_at)
      values (r.entry_id, p_week, 'MISSED', 'admin', false, 'missed', 'manual', now());
      insert into audit_log (actor, action, target_table, target_id, after)
      values (p_actor, 'deadline_sweep_miss', 'picks', r.entry_id::text,
              jsonb_build_object('week', p_week, 'entry_name', r.entry_name));
      v_count := v_count + 1;
    end loop;
    insert into audit_log (actor, action, target_table, target_id, note)
    values (p_actor, 'deadline_sweep', 'picks', p_week::text,
            format('week %s sweep: %s automatic losses', p_week, v_count));
  end if;

  return query select * from _sweep;
end $$;

-- The weeks editor now edits the two windows directly.
drop function if exists admin_update_week(int, text, timestamptz, boolean, text);
create or replace function admin_update_week(
  p_week int,
  p_early timestamptz,
  p_late timestamptz,
  p_confirmed boolean,
  p_actor text
) returns void
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_before jsonb;
  v_after jsonb;
begin
  if p_late < p_early then
    raise exception 'late deadline must not precede the early deadline';
  end if;

  select to_jsonb(w) into v_before from weeks w where w.week = p_week;
  if v_before is null then
    raise exception 'week % does not exist', p_week;
  end if;

  update weeks
     set early_deadline_at = p_early,
         late_deadline_at = p_late,
         deadline_at = p_late,
         confirmed = p_confirmed
   where week = p_week;

  select to_jsonb(w) into v_after from weeks w where w.week = p_week;
  insert into audit_log (actor, action, target_table, target_id, before, after)
  values (p_actor, 'update_week', 'weeks', p_week::text, v_before, v_after);
end $$;

do $$
begin
  execute 'revoke execute on function admin_update_week(int,timestamptz,timestamptz,boolean,text) from public';
  execute 'revoke execute on function pick_deadline(int,text) from public';
  begin
    execute 'revoke execute on function admin_update_week(int,timestamptz,timestamptz,boolean,text) from anon';
    execute 'grant execute on function admin_update_week(int,timestamptz,timestamptz,boolean,text) to authenticated';
    execute 'grant execute on function pick_deadline(int,text) to anon, authenticated';
  exception when undefined_object then
    null;
  end;
end $$;
