-- V2 Part G: Lynne's final 2025 sheet as a read-only archive.
-- GENERATED by scripts/archive/parse-2025.py from Football_2025-54.xlsx.
-- Status came from the FILL COLOR of the NAMES cells (red = OUT, yellow =
-- the 27 winners); week headers were mixed case and parsed
-- case-insensitively. She deletes eliminated entries as the season goes,
-- so only 56 of ~1,245 entries remain in the final sheet — a
-- missing entry is NOT a data error. Structurally separate from every
-- 2026 table; no write policies exist.

create table archive_2025_entries (
  lynne_number int primary key,
  entry_name text not null,
  fill text not null check (fill in ('red', 'yellow')),
  outcome text not null check (outcome in ('winner', 'out')),
  picks jsonb not null  -- 18 values: team name, 'BYE', 'OUT', or null
);

create table archive_2025_weekly (
  week int primary key check (week between 1 and 18),
  no_losses int,
  loss_bye int,
  out int
);

alter table archive_2025_entries enable row level security;
alter table archive_2025_weekly enable row level security;
create policy "public_read_archive_2025_entries" on archive_2025_entries
  for select using (true);
create policy "public_read_archive_2025_weekly" on archive_2025_weekly
  for select using (true);
grant select on archive_2025_entries, archive_2025_weekly to anon, authenticated;

insert into archive_2025_entries (lynne_number, entry_name, fill, outcome, picks) values
  (10, 'Alex-I', 'yellow', 'winner', '["Washington", "LA Rams", "Tampa Bay", "Houston", "Buffalo", "Green Bay", "Chicago", "New England", "LA Chargers", "Indianapolis", "Baltimore", "Detroit", "Seattle", "Denver", "San Francisco", "New Orleans", "Cincinnati", "Jacksonville"]'::jsonb),
  (13, 'Howard 1', 'yellow', 'winner', '["Arizona", "Dallas", "Seattle", "New England", "Detroit", "Green Bay", "Kansas City", "Indianapolis", "LA Rams", "Denver", "Houston", "Baltimore", "LA Chargers", "BYE", "San Francisco", "Buffalo", "Cincinnati", "Jacksonville"]'::jsonb),
  (32, 'Karen Meenan', 'yellow', 'winner', '["Denver", "Baltimore", "Tampa Bay", "Detroit", "Indianapolis", "Green Bay", "Kansas City", "New England", "LA Rams", "BYE", "Houston", "Seattle", "LA Chargers", "Buffalo", "Jacksonville", "San Francisco", "Cincinnati", "Minnesota"]'::jsonb),
  (38, 'Bill M 1', 'red', 'out', '["Washington", "Buffalo", "Tampa Bay", "Houston", "Dallas", "Indianapolis", "Pittsburgh", "New England", "LA Chargers", "Denver", "Green Bay", "Seattle", "Miami", "LA Rams", "Jacksonville", "Philadelphia", "Cincinnati", "Chicago"]'::jsonb),
  (44, 'Aiks - 1', 'yellow', 'winner', '["Arizona", "Baltimore", "Seattle", "Buffalo", "Indianapolis", "Green Bay", "Kansas City", "Philadelphia", "LA Rams", "Detroit", "New England", "San Francisco", "LA Chargers", "Denver", "Jacksonville", "Houston", "Cincinnati", "BYE"]'::jsonb),
  (60, 'Tim Aiken', 'yellow', 'winner', '["Arizona", "Baltimore", "Green Bay", "Buffalo", "Detroit", "Indianapolis", "Kansas City", "Philadelphia", "LA Rams", "Seattle", "New England", "San Francisco", "LA Chargers", "Denver", "Chicago", "Houston", "Dallas", "Jacksonville"]'::jsonb),
  (66, 'Tom Albero 2', 'red', 'out', '["Washington", "Detroit", "Tampa Bay", "Buffalo", "Minnesota", "Denver", "Chicago", "Indianapolis", "LA Rams", "Baltimore", "New England", "Seattle", "LA Chargers", "BYE", "Philadelphia", "Houston", "Jacksonville", "Cincinnati"]'::jsonb),
  (76, 'RJ Biondi 1', 'red', 'out', '["Arizona", "Dallas", "Seattle", "Buffalo", "Detroit", "LV Raiders", "New England", "Indianapolis", "LA Rams", "BYE", "Houston", "Baltimore", "LA Chargers", "Denver", "San Francisco", "Philadelphia", "Tampa Bay", "OUT"]'::jsonb),
  (78, 'Kyle Lipp', 'yellow', 'winner', '["Arizona", "Dallas", "Tampa Bay", "Detroit", "LA Rams", "LV Raiders", "New England", "Indianapolis", "LA Chargers", "Chicago", "Houston", "Seattle", "Miami", "Buffalo", "San Francisco", "Philadelphia", "Denver", "Jacksonville"]'::jsonb),
  (113, 'Gabi Kumar 4', 'yellow', 'winner', '["Arizona", "Dallas", "Seattle", "Buffalo", "Detroit", "Green Bay", "New England", "Indianapolis", "LA Rams", "BYE", "Baltimore", "San Francisco", "LA Chargers", "Denver", "Jacksonville", "Houston", "Cincinnati", "Minnesota"]'::jsonb),
  (114, 'Gabi Kumar 5', 'red', 'out', '["Arizona", "Dallas", "Seattle", "Green Bay", "Detroit", "Indianapolis", "Kansas City", "Buffalo", "LA Rams", "Baltimore", "New England", "San Francisco", "Jacksonville", "Denver", "Philadelphia", "Houston", "Tampa Bay", "OUT"]'::jsonb),
  (129, 'Greg Lurie', 'red', 'out', '["Philadelphia", "Dallas", "Buffalo", "Detroit", "Arizona", "Indianapolis", "New England", "Tampa Bay", "LA Rams", "Denver", "Baltimore", "Seattle", "Jacksonville", "Houston", "San Francisco", "Atlanta", "Cincinnati", "Kansas City"]'::jsonb),
  (174, 'David Lindsey 1', 'yellow', 'winner', '["Denver", "Arizona", "Tampa Bay", "Houston", "Detroit", "Indianapolis", "Chicago", "Kansas City", "LA Rams", "BYE", "New England", "Baltimore", "LA Chargers", "Seattle", "Philadelphia", "Buffalo", "Cincinnati", "Jacksonville"]'::jsonb),
  (181, 'MJ 1', 'red', 'out', '["Philadelphia", "Dallas", "Tampa Bay", "Buffalo", "Arizona", "Indianapolis", "Chicago", "New England", "LA Rams", "Denver", "Baltimore", "Seattle", "LA Chargers", "Green Bay", "San Francisco", "Houston", "Pittsburgh", "OUT"]'::jsonb),
  (217, 'Coco', 'red', 'out', '["Philadelphia", "Baltimore", "Green Bay", "Buffalo", "Detroit", "Pittsburgh", "New England", "Indianapolis", "LA Chargers", "Denver", "Houston", "Seattle", "Jacksonville", "LA Rams", "San Francisco", "Kansas City", "OUT", "OUT"]'::jsonb),
  (281, 'John Pach 1', 'red', 'out', '["Philadelphia", "Cincinnati", "Buffalo", "Detroit", "Indianapolis", "Green Bay", "Chicago", "Kansas City", "LA Rams", "Seattle", "New England", "BYE", "Miami", "Denver", "San Francisco", "Houston", "Jacksonville", "Dallas"]'::jsonb),
  (297, 'Liv P', 'yellow', 'winner', '["Philadelphia", "Baltimore", "Seattle", "Buffalo", "Detroit", "Green Bay", "Kansas City", "Indianapolis", "LA Chargers", "Denver", "New England", "BYE", "San Francisco", "LA Rams", "Jacksonville", "Houston", "Cincinnati", "Minnesota"]'::jsonb),
  (300, 'GNavo2', 'red', 'out', '["Denver", "Detroit", "Tampa Bay", "Buffalo", "Dallas", "Green Bay", "Kansas City", "Indianapolis", "LA Rams", "Baltimore", "New England", "Seattle", "LA Chargers", "BYE", "San Francisco", "Houston", "Pittsburgh", "OUT"]'::jsonb),
  (331, 'Sofia M2', 'yellow', 'winner', '["Washington", "Arizona", "Tampa Bay", "Detroit", "Indianapolis", "Green Bay", "Kansas City", "New England", "LA Rams", "Seattle", "BYE", "Baltimore", "LA Chargers", "Denver", "Jacksonville", "Houston", "Cincinnati", "Buffalo"]'::jsonb),
  (396, 'MannyT1', 'red', 'out', '["Washington", "LA Rams", "Tampa Bay", "Houston", "Arizona", "New England", "Kansas City", "Philadelphia", "Jacksonville", "Indianapolis", "Dallas", "San Francisco", "Miami", "Seattle", "Chicago", "Buffalo", "Detroit", "OUT"]'::jsonb),
  (414, 'RSmith', 'red', 'out', '["Arizona", "Dallas", "Tampa Bay", "Buffalo", "NY Giants", "Denver", "New England", "Indianapolis", "LA Rams", "Detroit", "Houston", "Seattle", "Jacksonville", "Miami", "Philadelphia", "San Francisco", "New Orleans", "Cincinnati"]'::jsonb),
  (435, 'Sean Hanson 3', 'yellow', 'winner', '["Pittsburgh", "LA Chargers", "Indianapolis", "Denver", "Tampa Bay", "Green Bay", "Kansas City", "New England", "LA Rams", "BYE", "Baltimore", "Detroit", "Seattle", "Buffalo", "San Francisco", "Houston", "Cincinnati", "Jacksonville"]'::jsonb),
  (484, 'Clem 3', 'yellow', 'winner', '["Arizona", "Baltimore", "Tampa Bay", "Buffalo", "Detroit", "Green Bay", "Kansas City", "Indianapolis", "LA Rams", "Denver", "New England", "Seattle", "LA Chargers", "BYE", "San Francisco", "Houston", "Cincinnati", "Jacksonville"]'::jsonb),
  (538, 'Liz Tarter 2', 'yellow', 'winner', '["Arizona", "Baltimore", "Seattle", "Detroit", "Minnesota", "LV Raiders", "New England", "Indianapolis", "LA Rams", "BYE", "Houston", "San Francisco", "LA Chargers", "Denver", "Philadelphia", "Buffalo", "Dallas", "Jacksonville"]'::jsonb),
  (561, 'N&N Manzi', 'red', 'out', '["Cincinnati", "Baltimore", "Tampa Bay", "Buffalo", "Indianapolis", "Green Bay", "Kansas City", "Philadelphia", "LA Rams", "Denver", "New England", "Seattle", "LA Chargers", "BYE", "San Francisco", "Houston", "Detroit", "OUT"]'::jsonb),
  (597, 'James O''Brien 1', 'red', 'out', '["Washington", "Baltimore", "Seattle", "Buffalo", "Detroit", "Green Bay", "San Francisco", "Indianapolis", "LA Rams", "BYE", "Dallas", "New England", "LA Chargers", "Denver", "Philadelphia", "Houston", "Tampa Bay", "OUT"]'::jsonb),
  (605, 'Aaron Silberstein', 'red', 'out', '["Philadelphia", "Baltimore", "Atlanta", "Buffalo", "Detroit", "Green Bay", "Kansas City", "Indianapolis", "LA Rams", "Seattle", "Pittsburgh", "San Francisco", "Jacksonville", "Denver", "Houston", "New Orleans", "New England", "Cincinnati"]'::jsonb),
  (616, 'Chas 1', 'yellow', 'winner', '["Washington", "Dallas", "Tampa Bay", "Buffalo", "Detroit", "Green Bay", "Kansas City", "Indianapolis", "BYE", "Denver", "Baltimore", "Seattle", "Miami", "LA Rams", "Philadelphia", "Houston", "New England", "Jacksonville"]'::jsonb),
  (622, 'Ronald Hensor', 'yellow', 'winner', '["Arizona", "Dallas", "Seattle", "LA Chargers", "Detroit", "Green Bay", "Kansas City", "Tampa Bay", "LA Rams", "Denver", "New England", "Baltimore", "San Francisco", "Buffalo", "Philadelphia", "Houston", "Jacksonville", "Atlanta"]'::jsonb),
  (629, 'Constable 1', 'red', 'out', '["Arizona", "LA Rams", "Buffalo", "Detroit", "Indianapolis", "Green Bay", "Kansas City", "Tampa Bay", "LA Chargers", "Seattle", "New England", "Baltimore", "Jacksonville", "Denver", "San Francisco", "Houston", "Pittsburgh", "OUT"]'::jsonb),
  (634, 'Christian C 1', 'red', 'out', '["Arizona", "Baltimore", "Seattle", "Buffalo", "Detroit", "LA Rams", "Kansas City", "New England", "BYE", "Indianapolis", "Houston", "San Francisco", "LA Chargers", "Denver", "Jacksonville", "Philadelphia", "Tampa Bay", "OUT"]'::jsonb),
  (683, 'Patrick Notaro', 'red', 'out', '["Pittsburgh", "Baltimore", "Seattle", "Detroit", "Buffalo", "Indianapolis", "Philadelphia", "Tampa Bay", "LA Chargers", "LA Rams", "San Francisco", "Atlanta", "Jacksonville", "Denver", "Chicago", "Houston", "New England", "Cincinnati"]'::jsonb),
  (712, 'Chris S 2', 'red', 'out', '["Arizona", "Buffalo", "Kansas City", "Detroit", "Philadelphia", "Green Bay", "Denver", "Indianapolis", "Baltimore", "Seattle", "San Francisco", "New England", "LA Chargers", "LA Rams", "Chicago", "Houston", "Tampa Bay", "OUT"]'::jsonb),
  (720, 'Chicken Nugget Champs', 'red', 'out', '["Washington", "Baltimore", "LA Chargers", "Detroit", "Indianapolis", "Pittsburgh", "Cleveland", "Philadelphia", "LA Rams", "Denver", "New England", "Seattle", "Jacksonville", "BYE", "Houston", "Buffalo", "Cincinnati", "Dallas"]'::jsonb),
  (771, 'Mike Erickson', 'red', 'out', '["Philadelphia", "Baltimore", "Buffalo", "Houston", "Detroit", "Green Bay", "NY Jets", "Kansas City", "LA Rams", "Seattle", "New England", "San Francisco", "LA Chargers", "Denver", "Chicago", "Cincinnati", "Tampa Bay", "OUT"]'::jsonb),
  (858, 'Baby Keough', 'yellow', 'winner', '["Jacksonville", "Cincinnati", "Atlanta", "Buffalo", "Detroit", "Green Bay", "Kansas City", "Indianapolis", "LA Rams", "Seattle", "New England", "Baltimore", "LA Chargers", "Denver", "Philadelphia", "Houston", "Dallas", "Minnesota"]'::jsonb),
  (873, 'Eddie McD', 'yellow', 'winner', '["Denver", "Arizona", "Tampa Bay", "Buffalo", "Detroit", "Pittsburgh", "New England", "Indianapolis", "LA Rams", "Seattle", "BYE", "Baltimore", "LA Chargers", "Green Bay", "San Francisco", "Houston", "Cincinnati", "Jacksonville"]'::jsonb),
  (900, 'Mike Q', 'yellow', 'winner', '["Washington", "Buffalo", "Tampa Bay", "Detroit", "Arizona", "Pittsburgh", "Kansas City", "Indianapolis", "LA Rams", "Denver", "New England", "Baltimore", "LA Chargers", "Seattle", "Philadelphia", "Houston", "Cincinnati", "Jacksonville"]'::jsonb),
  (903, 'Nantucket', 'yellow', 'winner', '["Arizona", "Dallas", "Tampa Bay", "Buffalo", "Detroit", "Green Bay", "New England", "Indianapolis", "LA Rams", "BYE", "Baltimore", "Seattle", "LA Chargers", "Denver", "San Francisco", "Houston", "Cincinnati", "Jacksonville"]'::jsonb),
  (905, 'Nick B', 'red', 'out', '["Philadelphia", "Dallas", "Seattle", "Buffalo", "Detroit", "Green Bay", "Kansas City", "Indianapolis", "LA Rams", "BYE", "New England", "Baltimore", "LA Chargers", "Denver", "Jacksonville", "Houston", "Tampa Bay", "OUT"]'::jsonb),
  (909, 'Patrick B', 'red', 'out', '["Denver", "Detroit", "Philadelphia", "Buffalo", "Minnesota", "Indianapolis", "Green Bay", "BYE", "New England", "Seattle", "Baltimore", "San Francisco", "Miami", "LA Rams", "Jacksonville", "Houston", "Tampa Bay", "OUT"]'::jsonb),
  (964, 'Heather Seckel', 'yellow', 'winner', '["Cincinnati", "Dallas", "Seattle", "New England", "Minnesota", "Pittsburgh", "Chicago", "Indianapolis", "LA Rams", "Detroit", "Baltimore", "San Francisco", "LA Chargers", "Denver", "Philadelphia", "Houston", "BYE", "Jacksonville"]'::jsonb),
  (980, 'Anthony DellaPia 5', 'red', 'out', '["Arizona", "Dallas", "Kansas City", "Houston", "Indianapolis", "Green Bay", "New England", "Philadelphia", "LA Rams", "Detroit", "Baltimore", "BYE", "Seattle", "Denver", "San Francisco", "Buffalo", "Tampa Bay", "OUT"]'::jsonb),
  (1006, 'Alexc 1', 'red', 'out', '["Philadelphia", "Baltimore", "Kansas City", "Buffalo", "Detroit", "Green Bay", "New England", "Indianapolis", "LA Rams", "Bye", "Houston", "Seattle", "LA Chargers", "Denver", "Jacksonville", "San Francisco", "Tampa Bay", "OUT"]'::jsonb),
  (1037, 'Nolan Lawrence 1', 'red', 'out', '["Minnesota", "LA Chargers", "Atlanta", "Buffalo", "Detroit", "Green Bay", "Kansas City", "Indianapolis", "Denver", "LA Rams", "Dallas", "Baltimore", "New England", "Miami", "Jacksonville", "Houston", "Seattle", "Cincinnati"]'::jsonb),
  (1072, 'Marilyn Wass', 'red', 'out', '["Philadelphia", "Buffalo", "Tampa Bay", "Detroit", "Indianapolis", "Green Bay", "Chicago", "Kansas City", "LA Rams", "Denver", "Baltimore", "Seattle", "New England", "BYE", "San Francisco", "Houston", "Pittsburgh", "OUT"]'::jsonb),
  (1077, 'Adam Huewe', 'red', 'out', '["Denver", "Baltimore", "Seattle", "Buffalo", "Arizona", "Pittsburgh", "Kansas City", "Tampa Bay", "LA Chargers", "Detroit", "Houston", "San Francisco", "New England", "LA Rams", "Jacksonville", "Philadelphia", "New Orleans", "Cincinnati"]'::jsonb),
  (1085, 'Sebastian Dobes', 'red', 'out', '["Philadelphia", "Arizona", "Seattle", "Houston", "Detroit", "LA Rams", "Chicago", "Indianapolis", "LA Chargers", "BYE", "New England", "Baltimore", "Jacksonville", "Denver", "San Francisco", "Buffalo", "Tampa Bay", "OUT"]'::jsonb),
  (1100, 'Anthony Venafro', 'yellow', 'winner', '["Washington", "Arizona", "Tampa Bay", "Denver", "Indianapolis", "Pittsburgh", "Kansas City", "New England", "LA Rams", "Seattle", "Baltimore", "Detroit", "LA Chargers", "BYE", "San Francisco", "Houston", "Jacksonville", "Buffalo"]'::jsonb),
  (1109, 'Tricia Costa', 'yellow', 'winner', '["Jacksonville", "Baltimore", "Tampa Bay", "Denver", "Indianapolis", "Washington", "Kansas City", "New England", "LA Rams", "Seattle", "Pittsburgh", "Detroit", "LA Chargers", "Green Bay", "San Francisco", "Houston", "Cincinnati", "Buffalo"]'::jsonb),
  (1110, 'Damon Dambrosio 1', 'yellow', 'winner', '["Philadelphia", "Baltimore", "Tampa Bay", "Buffalo", "Detroit", "Green Bay", "Kansas City", "Indianapolis", "LA Rams", "Denver", "New England", "Seattle", "LA Chargers", "BYE", "San Francisco", "Houston", "Dallas", "Jacksonville"]'::jsonb),
  (1128, 'Mazz', 'yellow', 'winner', '["Denver", "Baltimore", "Tampa Bay", "Buffalo", "Detroit", "Indianapolis", "Kansas City", "Philadelphia", "LA Rams", "BYE", "New England", "Seattle", "LA Chargers", "Green Bay", "San Francisco", "Houston", "Cincinnati", "Jacksonville"]'::jsonb),
  (1158, 'Sondra F', 'yellow', 'winner', '["Jacksonville", "Baltimore", "Indianapolis", "Chicago", "NY Giants", "Green Bay", "Kansas City", "Buffalo", "LA Chargers", "Denver", "New England", "Detroit", "San Francisco", "Seattle", "Philadelphia", "Houston", "Dallas", "LA Rams"]'::jsonb),
  (1161, 'Roberto 1', 'yellow', 'winner', '["Philadelphia", "Baltimore", "Tampa Bay", "Buffalo", "Arizona", "Indianapolis", "New England", "Kansas City", "LA Rams", "Denver", "Houston", "Detroit", "LA Chargers", "Seattle", "Jacksonville", "San Francisco", "Cincinnati", "Minnesota"]'::jsonb),
  (1176, 'Jay D 1', 'yellow', 'winner', '["Philadelphia", "Dallas", "Tampa Bay", "Detroit", "LA Rams", "Denver", "Green Bay", "Indianapolis", "San Francisco", "Chicago", "Pittsburgh", "Baltimore", "LA Chargers", "Seattle", "Jacksonville", "Houston", "Cincinnati", "New England"]'::jsonb),
  (1237, 'Amy E 3', 'red', 'out', '["Arizona", "Dallas", "Atlanta", "Denver", "Indianapolis", "Pittsburgh", "Green Bay", "New England", "LA Rams", "Detroit", "Houston", "Baltimore", "LA Chargers", "Seattle", "Chicago", "Buffalo", "Jacksonville", "Cincinnati"]'::jsonb);

insert into archive_2025_weekly (week, no_losses, loss_bye, out) values
  (1, 1206, 42, 0),
  (2, 1161, 83, 4),
  (3, 845, 378, 25),
  (4, 641, 491, 117),
  (5, 347, 580, 321),
  (6, 296, 517, 435),
  (7, 278, 511, 459),
  (8, 157, 365, 726),
  (9, 109, 287, 852),
  (10, 50, 207, 991),
  (11, 39, 211, 998),
  (12, 34, 208, 1006),
  (13, 27, 178, 1043),
  (14, 3, 53, 1192),
  (15, 3, 53, 1192),
  (16, 3, 52, 1193),
  (17, 1, 37, 1210),
  (18, 0, 27, null);
